### ISSUE TITLE
App crashing on launch

### ISSUE THREAD

**Issue by ccdffddfddfdsfedeee** [iandwelker/smserver#1]
iPhone 8, iOS 13.3

**Comment by iandwelker** [comment]
To diagnose this, I’ll need the answers to a few questions: 
What jailbreak are you using?
Do you have libsmserver, libmryipc, and AppSync Unified installed?
What method did you use to install the app?
Have you verified that you’re on the latest version of the app that is available on the repo?

**Comment by ccdffddfddfdsfedeee** [comment]
Jailbreak: Checkra1n
All three are installed
Installed the files with filza
Latest version

**Comment by iandwelker** [comment]
Could you try installing the app .deb with a package manager? I've had another user report that the app wouldn't launch when installed via filza, but worked fine when installed via Zebra.

**Comment by ccdffddfddfdsfedeee** [comment]
The app still crashes when installing it with zebra and disabling all tweaks with icleaner

**Comment by iandwelker** [comment]
Alright, then could you complete the following steps:
1. Download the package 'oslog' from zebra
2. SSH into your device
3. Run this command: 'oslog | grep -i -e "smserver" -e "nlgf" > /var/mobile/Documents/smserver.log'
4. Grab the document that was created at /var/mobile/Documents/smserver.log and upload it here or DM it to me directly on Reddit (u/Janshai)
I'll look at the log and get back to you on possible solutions.

**Comment by ccdffddfddfdsfedeee** [comment]
File link: https://pastebin.com/P8zt3XCM

**Comment by iandwelker** [comment]
I've uploaded new versions of both SMServer and libsmserver. Could you completely uninstall the old versions of both, then install the new versions and let me know if this fixes the problem?

**Comment by ccdffddfddfdsfedeee** [comment]
It is still not working

**Comment by iandwelker** [comment]
I'm sorry to ask again (and that this is taking so long to resolve), but could you run through the following steps:
1. SSH into your device
2. Run the command: 'oslog | grep -i -e "smserver" -e "nlgf" -e "mryipc" > /var/mobile/Documents/smserver.log', and don't cancel this command until you've finished the rest of the steps.
3. Respring your device 
4. Launch SMServer, and let it crash.
5. Stop the command that you launched in step 2.
6. Upload the file at /var/mobile/Documents/smserver.log

Your previous log suggested that libsmserver and/or libmryipc weren't working, but if the app is still crashing in the new version, then that's not the case. I'll look at the new log as soon as you send it over :)

**Comment by ccdffddfddfdsfedeee** [comment]
https://pastebin.com/CHfyfZbx

**Comment by iandwelker** [comment]
I realized I was building my project for minimum deployment of 13.4; I decreased it to 13.3 and pushed a new .deb that could be compatible. Could you try it out?

If this .deb doesn't work, please do the following: 
- Get a crash report from an app like cr4shed and upload it here
- run the command `ls -la /Applications/SMServer.app/SMServer` on your phone and upload the output here

**Comment by ccdffddfddfdsfedeee** [comment]
The app is still crashing, and cr4shed did not show anything

The command says:
"-rwsrwsrwt 1 root mobile 1333600 Jul 11 17:06 /Applications/SMServer.app/SMServer*"

**Comment by iandwelker** [comment]
I looked through your crash logs a bit more, and it appears you may be having some tweaks that are trying to inject, and also that screen time may be having some effect on the app. If you have screen time enabled on your device, do you think you could try turning it off, and also try running the app in safe mode/with tweaks disabled (after uninstalling the app & tweak and reinstalling the latest versions, of course)?

**Comment by ccdffddfddfdsfedeee** [comment]
Solved! The latest version fixed the problem

**Comment by iandwelker** [comment]
That's great to hear! Before I close this, I just want to check: did you have to run it with tweaks disabled/screen time off or did the latest version, without any modifications, work fine?

**Comment by ccdffddfddfdsfedeee** [comment]
The latest version without any tweaks disabled is working
