### ISSUE TITLE
No chats showing up

### ISSUE THREAD

**Issue by The-SamminAter** [iandwelker/smserver#10]
- iPhone XS
- unc0ver v4.3.1
- iOS 13.2.3
- installed from Twickd

When accessing the site on a desktop computer, no chats show up.

I'm able to message someone by creating a new chat, but the new chat doesn't show up in the chats section (on the website).

**Comment by iandwelker** [comment]
If you look near the bottom of the readme, it lists what information should be included when filing an issue. Do you think you could add all that information here?

**Comment by The-SamminAter** [comment]
Sorry, I didn't see that originally. I've updated my original comment

**Comment by iandwelker** [comment]
Could you try updating to the latest version of unc0ver? Some other users (See issue #7 ) were encountering the same issue, until they updated to the latest version of unc0ver.

**Comment by The-SamminAter** [comment]
I'm not sure that I can, as last time I tried running the latest unc0ver it didn't work.

**Comment by iandwelker** [comment]
Well, there are a few other things we can check to see if I can solve this, but if this issue shows all the symptoms of the other one, there may not be anything I can do to fix this.

So, the things we can check:
1. Are there any errors in your browser's console while using SMServer?
2. Please visit smserver's root site (your IP address + port, e.g. `192.168.x.x:8741`), with `/requests?chat=0` appended onto the end (for a full url of something like `192.168.x.x:8741/requests?chat=0`). What does it show on the web page?
3. If number 1 shows no errors and number 2 shows `{ "chats": [ ] }`, please get a log as described underneath the `How to file an issue` section of the readme and attach it here (If you see any personal information, feel free to filter it out, but I expect this log will have no personal information)

**Comment by The-SamminAter** [comment]
1. I am getting no errors
2. This is what it shows on the webpage:
```
{ "chats": [

]
}
```
3. Following the instructions on getting a log didn't produce any text :/

**Comment by iandwelker** [comment]
When getting the log, you made sure you were root while running the command, right? And you didn't respring while the command was running?

**Comment by The-SamminAter** [comment]
I'm pretty sure it was being ran as root, and I didn't respring what it was running.

Either way, I just updated unc0ver and jailbroke with it, so I'll now try and see if the issue has been solved.

**Comment by The-SamminAter** [comment]
It works, this is definitely an issue with older versions of unc0ver.
