### ISSUE TITLE
Request to display entered messages properly

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#100]
![List SMServer](https://user-images.githubusercontent.com/53708281/108802385-27379480-7566-11eb-88eb-176dd3f55cf6.JPG)
![List WebMessage](https://user-images.githubusercontent.com/53708281/108802387-2868c180-7566-11eb-9ce2-7a665059e3f6.JPG)
![List BlueBubbles](https://user-images.githubusercontent.com/53708281/108802390-2a328500-7566-11eb-8525-7aec006180dd.JPG)
Here is an example of a message in SMServer, WebMessage, and BlueBubbles Desktop

https://musictaste.space/ also here is the website that was in those messages in case you're interested

**Comment by iandwelker** [comment]
Version 0.7.4 is out on twickd.

**Comment by CSab6482** [comment]
> Here are some pictures that hopefully show what I mean.
> <img alt="PNG image" width="375" src="https://user-images.githubusercontent.com/53708281/113068076-8d2dc200-918b-11eb-8c57-8077d8985782.png">
> ![Entered bottom](https://user-images.githubusercontent.com/53708281/113441156-c8163c80-93bb-11eb-92ac-5ae27b64a408.png)
> I first noticed this when submitting [this comment](https://github.com/sgtaziz/WebMessage/issues/128#issuecomment-810634610)

Originally posted in https://github.com/sgtaziz/WebMessage/issues/152
