### ISSUE TITLE
SMServer is lagging in Chromium Browsers (especially upon video playback)

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#102]
I noticed some stalling while scrolling in a group chat, but nothing major. Then I tried to play a video and noticed that it was extremely choppy. This may just be a problem with my computer's specs which I'll post below, but I remember video playback being much smoother.
![Specs](https://user-images.githubusercontent.com/53708281/109001345-d366a180-7672-11eb-9df3-f84ff16ef348.JPG)

https://user-images.githubusercontent.com/53708281/109001053-72d76480-7672-11eb-942e-e9e30603ea07.mp4

https://user-images.githubusercontent.com/53708281/108585868-d3843b80-7318-11eb-910d-245a4bf79034.mp4

There's the video that I was playing for comparison, which is especially evident at the points where I was typing. In that specific video the SMServer tab and the screen recorder were the only things I had running on my computer. I just remembered the video that inspired me to open this ticket, so now I will screen record that one (with three GitHub pages open in the background for reference).

https://user-images.githubusercontent.com/53708281/109002336-137a5400-7674-11eb-8ce2-58a708c674d3.mp4

https://user-images.githubusercontent.com/53708281/109002348-18d79e80-7674-11eb-968d-44eb468191ef.mp4

and as one of my favorite YouTubers, LockPickingLawyer, likes to say "That was not a fluke". I've played the Among us video a few times and every time it's the same frame rate.

Scrolling and video playback works perfectly in FireFox. Maybe this is a sign.

**Comment by iandwelker** [comment]
Sorry, I'm just not seeing this at all, in any chromium-based browser. Have you tried the same browser on different computers to see if it's an issue with just that one laptop?

**Comment by CSab6482** [comment]
That was a good suggestion, it worked perfectly on another computer. I'm not sure what it could be.
![no video](https://user-images.githubusercontent.com/53708281/109396140-23a56400-78fe-11eb-8a13-ae24a61cf086.JPG)
I tested some videos, but I got this message for two .MOV videos in FireFox that did play in Chrome.
![mov sms](https://user-images.githubusercontent.com/53708281/109396151-34ee7080-78fe-11eb-961c-0ee1f63bf9bc.JPG)
Also, one video showed up as an audio file, I'm not sure why.

Here is what that same glitched video looks like in WebMessage
![mov](https://user-images.githubusercontent.com/53708281/109396165-46377d00-78fe-11eb-8a6b-9019028db59c.JPG)
Downloading it from WebMessage lets me play the video in Windows (though there is a blank file preview). I cannot download it from SMServer because of the current chromium bug and that pop up in FireFox. Let me know if I should open a ticket for this

**Comment by sgtaziz** [comment]
QuickTime mov files are not supported by Chromiun, or any browser currently. It's Apple's own format and licensing on it is limited.

The only way to get those videos to work is to perform some sort of conversion on them on the fly iOS side, which would use up quite a big amount of resources.

As far as this current issue goes, maybe look into unloading the video if it's not used? I'm not exactly sure how this is handled @iandwelker, but I've experienced the same issue in past projects. The video would stay in memory and cause some lag. Not having hrdware acceleration also makes the issue much worse, so maybe make sure it's enabled in your browser and that your PC supports it.

**Comment by CSab6482** [comment]
https://github.com/open-imcore/imessage-rest/issues/12
Would this be any help?

**Comment by sgtaziz** [comment]
All this is mentioning is adding a parameter to transcode or convert the video file. It's definitely possible, but should definitely be opt-in only as it can drain your battery

**Comment by CSab6482** [comment]
> QuickTime mov files are not supported by Chromiun, or any browser currently. It's Apple's own format and licensing on it is limited.
> 
> The only way to get those videos to work is to perform some sort of conversion on them on the fly iOS side, which would use up quite a big amount of resources.
> 
> As far as this current issue goes, maybe look into unloading the video if it's not used? I'm not exactly sure how this is handled @iandwelker, but I've experienced the same issue in past projects. The video would stay in memory and cause some lag. Not having hrdware acceleration also makes the issue much worse, so maybe make sure it's enabled in your browser and that your PC supports it.

Last semester, I had to turn off hardware acceleration for the images in one of my exams to display properly, and turning it back on fixed this issue. Thank you 🙏. @iandwelker, should I close this ticket and open a new one for [this comment?](https://github.com/iandwelker/smserver/issues/102#issuecomment-787114198)

**Comment by zlshames** [comment]
Yep, in BlueBubbles, we use ffmpeg to convert the .mov files to .mp4 files. It's really the only way to do it at the moment since .mov isn't exactly supported natively on web (not sure about Android)

**Comment by CSab6482** [comment]
> Yep, in BlueBubbles, we use ffmpeg to convert the .mov files to .mp4 files. It's really the only way to do it at the moment since .mov isn't exactly supported natively on web (not sure about Android)

On Android it downloads as an MOV, and (on my phone at least), the video plays/behaves normally. Would it be possible to have the videos converted to MP4 on Android too (toggleable) or is it too inefficient/resource intensive?

**Comment by zlshames** [comment]
Also, to add to this, I _think_ I did something very similar with sound files for Apple's sound format. Had to convert it to an mp3 for voice memos and what not.

**Comment by iandwelker** [comment]
ay we got the whole squad discussing this issue, huh? just need to have Eric make a comment and we'll have everybody in on it

> Last semester, I had to turn off hardware acceleration for the images in one of my exams to display properly, and turning it back on fixed this issue. Thank you 🙏. \@iandwelker, should I close this ticket and open a new one for this comment?

Glad to hear it's not an SMServer issue. And closing this issue to open another one for that comment would be preferable, yes. I'll definitely take a look into it.
