### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by juan2three** [iandwelker/smserver#103]
iPhone 12, iOS 14.1. Libsmserver and SMServer installed

**Comment by iandwelker** [comment]
Do you think you'd be able to attach a crash report? Also, do you have libMRYIPC installed? If so, what version is it?

**Comment by juan2three** [comment]
libMRYIPC V2.0, cr4shed is currently not supported on 14.1. do you have a way I can share the crash reports?

**Comment by iandwelker** [comment]
I think cr4shed may have just started working with the latest unc0ver version, according to a few people on reddit. However, if it still doesn't work for you, you can also get crash logs by opening your settings app and going to Privacy > Analytics & Improvements > Analytics Data and finding the crash report there.

**Comment by juan2three** [comment]
It just randomly started working yesterday. We can go ahead and close this for now
