### ISSUE TITLE
can't install ipa

### ISSUE THREAD

**Issue by 22350** [iandwelker/smserver#104]
crashes altserver and installonair.com doesn't recognize ipa not recognized

**Comment by iandwelker** [comment]
[SMServer_0.7.4.zip](https://github.com/iandwelker/smserver/files/6113846/SMServer_0.7.4.zip)

Could you try to install this version (you'll need to change the extension to `ipa` after downloading it)? It's a development version, so some features won't work if you leave it installed, but I just need to verify that it will successfully install.

**Comment by iandwelker** [comment]
I've verified the 0.7.4 release ipa can install correctly. Closing issue.
