### ISSUE TITLE
Unable to find libmryipc to install libsmserver to have SMServer to function

### ISSUE THREAD

**Issue by eliluong** [iandwelker/smserver#106]
Hi, I can repost to libsmserver repo if that is better location for this question. I have iPad Pro gen1 on iOS 13.6 that was jailbroken with checkra1n and has Cydia installed. I verified BigBoss and also Dynastic repos are present. But under search, libmryipc does not appear. Also verified under the repos themselves by listing all packages, that libmryipc is not present. Also further verified under Installed Packages with Expert toggled that libmryipc is not installed. Does SMServer support the iPad, or is it only iPhone? Thanks.

**Comment by iandwelker** [comment]
Yeah, it's not showing up for me either -- not quite sure why. In the meantime, until it appears again, you can download the latest deb from [here](https://github.com/Muirey03/MRYIPC/releases/tag/20200717153101-189b5f1), install it to your phone, then try to install SMServer again and it should work just fine.

SMServer supports iPad as well as iPhone.

**Comment by eliluong** [comment]
Thanks, I will do that. I have another install issue now, but I will open a new issue for that and will close this.
