### ISSUE TITLE
Images sent with subject line text but no main body text don't show tapbacks | Images sent with both subject line text and main body text send with the text together instead of apart

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#110]
This issue is similar, but not the same as [this BlueBubbles issue](https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/197) and [this WebMessage issue](https://github.com/sgtaziz/WebMessage/issues/143). The main difference is that SMServer does show the text, it just doesn't show the text in the correct order, nor does it show any tapbacks.

Here are pictures from my Mac, iPhone, and SMServer client window.
For the piñata picture - tapback_guid="p:0/C93C7CD5-9266-414B-BCC6-AD016E6A4D5D"
For the "lose my mind" text - tapback_guid="p:1/C93C7CD5-9266-414B-BCC6-AD016E6A4D5D"
![Screen Shot 2021-03-18 at 3 55 54 PM](https://user-images.githubusercontent.com/53708281/111696033-2a8f0a80-880a-11eb-8cab-51b71608fb86.png)
![PNG image](https://user-images.githubusercontent.com/53708281/111696039-2c58ce00-880a-11eb-867c-f0cd0f356c35.png)
![SMServer p](https://user-images.githubusercontent.com/53708281/111696045-2ebb2800-880a-11eb-9efb-c93205ecee25.png)
And then here is an example of an image sent with both subject line text and main body text
For the slowness report picture - tapback_guid="p:0/EBF4C265-6DAE-4181-BF87-4C6E4DB19FBE"
For the "Jason from homework" text - tapback_guid="p:1/EBF4C265-6DAE-4181-BF87-4C6E4DB19FBE"
![Screen Shot 2021-03-18 at 3 56 52 PM](https://user-images.githubusercontent.com/53708281/111696286-85286680-880a-11eb-8580-9cca02971856.png)
![PNG image 1](https://user-images.githubusercontent.com/53708281/111696292-86f22a00-880a-11eb-90bb-6f4266650ba6.png)
![SMServer J](https://user-images.githubusercontent.com/53708281/111696293-88bbed80-880a-11eb-9bf5-a1bae436d497.png)

**Comment by EricRabil** [comment]
Message subjects should be presented at the first part of the message, regardless of what that part is. In this case, if there is an image, a text chat item should bore ese the image with a subject and no main content.

**Comment by iandwelker** [comment]
Alright, I found the issue and it looks like this should be fixed in the next version (don't worry, it should be coming out soon; I know it's been like months lol).

**Comment by CSab6482** [comment]
This is almost perfect. For some strange reason, SMServer added an extra space under my hello message. I'm not sure what could have caused this. Similar to my [troll face sticker](https://github.com/iandwelker/smserver/issues/76#issuecomment-829795603), the conversation history says that I applied a tapback to nothing
![Almost](https://user-images.githubusercontent.com/53708281/116765449-27835e80-a9f3-11eb-8ed6-82284b824011.png)
![PNG Image](https://user-images.githubusercontent.com/53708281/116765448-26eac800-a9f3-11eb-8618-0a4afe529d08.png)
![PNG image (1)](https://user-images.githubusercontent.com/53708281/116765530-9fea1f80-a9f3-11eb-8125-b0ea6b7d3655.png)
Some information about the messages.

"Hello" - tapback_guid="p:-1/1271A236-D9CF-457E-BA31-FB1D77FB2F95"
" " - tapback_guid="p:0/1271A236-D9CF-457E-BA31-FB1D77FB2F95"

**Comment by CSab6482** [comment]
This issue has been fixed. The comment above is more inline with issue #124
