### ISSUE TITLE
Question - What happened to Twickd 😳

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#112]
![image](https://user-images.githubusercontent.com/53708281/111729992-c50d3f00-8846-11eb-827e-14b1e969b0e1.png)

**Comment by iandwelker** [comment]
https://www.datacenterknowledge.com/uptime/fire-has-destroyed-ovh-s-strasbourg-data-center-sbg2 &mdash; I think they were affected by this. [twickd.com](https://twickd.com) shows that they're having some sort of ongoing hosting issue.

**Comment by CSab6482** [comment]
Oh man! It's good to see no one was injured, hopefully everything gets back up (physically and digitally) soon
