### ISSUE TITLE
Question - Is this as good as browser notifications get?

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#119]
With WebMessage's new feature that has contact photos in notifications, it feels much more like I am using native iMessage on my Windows computer. I was wondering, is it possible to implement such a thing for SMServer, or do browser notifications not allow for this level of customizability?
![Screenshot 2021-04-09 210006](https://user-images.githubusercontent.com/53708281/114253698-2f625c80-9979-11eb-9c74-0ec3b7bf3af9.png)
![Screenshot 2021-04-09 210606](https://user-images.githubusercontent.com/53708281/114253701-312c2000-9979-11eb-8c63-0babc8897cd4.png)

**Comment by iandwelker** [comment]
Thanks for pointing this out; I simply hadn't considered adding images for notifications like that. It was super easy to get implemented, and should be included in the next version.

**Comment by CSab6482** [comment]
This works! However, when someone sends a text in a group chat that has a group chat photo, the notification has the image of the group chat photo, not the individual. Is this expected behavior?

**Comment by iandwelker** [comment]
I personally think it should be expected behavior, to indicate what chat it's sent in, though the sender name should also indicate that it's a group chat, so maybe it's redundant? What do you think? Would it work better if the image was always the profile picture of whoever sent it, and then the sender name in the notification would show the group chat name?

**Comment by CSab6482** [comment]
When it comes to things that can be good both one way or the other, I think it is best to make a toggle. In the best case scenario, I would have the small photo where the browser icon goes be the group chat photo and the big photo be the contact photo, but I understand that that isn’t possible. I would be okay with it being left as it is, but if possible, a toggle for either the group chat photo or the individual contact photo would be very cool.

**Comment by iandwelker** [comment]
I also think a toggle would be nice (I'm generally a fan of more customizability), but I feel like this is too small of a part of the app to make a toggle for. Both discussed options provide about the same amount of functionality and usability, and I don't see many people having strong feelings about which one of these options they'd like to use, so I think I'll leave the notifications as I set them, without a toggle. I appreciate the input, though.
