### ISSUE TITLE
[Feature Request] Handle the tapback menu for messages at the top of the conversation

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#120]
> I was inspired to look for this because of [this ticket](https://github.com/sgtaziz/WebMessage/issues/141). Below is a video of how it behaves in SMServer.
> 
>  https://user-images.githubusercontent.com/53708281/114603970-5fa24780-9c66-11eb-9d75-6477f5af59f0.mp4

Originally posted in https://github.com/open-imcore/imcore.react/issues/27

This works well most of the time because of how SMServer pushes messages down when bringing up the tapback menu, but sometimes it's still unreachable.

**Comment by CSab6482** [comment]
One thing I noticed is that on macOS (at least my version of Mojave), this bug behaves the same, but on iOS, it works pretty well.

https://user-images.githubusercontent.com/53708281/114624953-8751d980-9c7f-11eb-8654-5f885437cd1c.mp4

https://user-images.githubusercontent.com/53708281/114624997-989ae600-9c7f-11eb-880a-8ad04bbdc37c.MP4

**Comment by iandwelker** [comment]
Sorry, I'm somewhat confused &mdash; is it not possible to scroll up to view the tapback menu? Or were you just expecting that the tapback menu would show even when only part of the text was visible?

**Comment by CSab6482** [comment]
Yes, the second part. I'm requesting that the tapback menu lowers the text enough to have the menu show up in use cases where the text is at the top. Or that it just goes through the top menu like it does on iOS. It is possible to scroll up, but sometimes this is just how the text naturally shows up when scrolled all the way down.

**Comment by iandwelker** [comment]
Sorry, I simply don't think it's worth it to add something in to specifically scroll the main view down when you can easily do that manually. Closing this issue as a wontfix.
