### ISSUE TITLE
Web Client Auto Scroll Up

### ISSUE THREAD

**Issue by jlesko2** [iandwelker/smserver#121]
When I click on a chat, the web client automatically scrolls up and does not show the latest messages in the thread. 

**Jailbreak:** Checkra1n
**iOS Version:** 13.2.2
**iPhone:** 7 Plus
**Installation Method:** Manually installed .deb packages (downloaded from GitHub releases) with filza
**SMServer:** 0.7.4
**libsmserver:** 0.6.4

**Comment by iandwelker** [comment]
Could this be due to images loading? I've noticed that in conversations where there are a lot of images/videos, the conversation scrolls to the bottom immediately, but then as more media loads, the texts appear to scroll up slightly to accommodate for what's being loaded in. Is this the same situation?

**Comment by jlesko2** [comment]
> Could this be due to images loading? I've noticed that in conversations where there are a lot of images/videos, the conversation scrolls to the bottom immediately, but then as more media loads, the texts appear to scroll up slightly to accommodate for what's being loaded in. Is this the same situation?

Yes, it does seem to only happen on threads where there are images. On threads with a lot of images, it scrolls up quite a bit. Is there anyway to address this client side?

**Comment by iandwelker** [comment]
> Is there anyway to address this client side?

I don't think so, sadly. It would be really ideal if I could make the loading images not change the scroll position, but I haven't found an easy way. I could lock the scroll position to the bottom of the chat until all images finish loading in, but that would be bad for various other reasons and create another problem to solve.

I think I'll close this issue for now. If you find something else to add to this, feel free to comment or reopen; I would also like a fix to this but I just don't think it's possible atm.
