### ISSUE TITLE
No errors, No crash, just doesn't work

### ISSUE THREAD

**Issue by nab138** [iandwelker/smserver#126]
So I saw this tweak and got super excited. I installed it with zebra and started the server.
My phone was on WIFI.
I got the IP and port combo and went to it on my PC, on the same WIFI, and it loaded for a long time until eventually saying "This page isnt working: 192.168.1.210 didn't send any data"
I even tried using Oslog (SSHing into my phone worked so the devices were on the same network) and it said
`<Debug>: SMServer_app: Attempting to load server and socket...
May  3 07:18:33 Nicks-iPhone-S-E SMServer(com.ianwelker.smserver.debugging)[14157] <Debug>: SMServer_app: Got past adding all the handlers.
May  3 07:18:33 Nicks-iPhone-S-E SMServer(com.ianwelker.smserver.debugging)[14157] <Debug>: SMServer_app: Started websocket successfully.
May  3 07:18:33 Nicks-iPhone-S-E SMServer(com.ianwelker.smserver.debugging)[14157] <Debug>: SMServer_app: Successfully started server and socket`
But still didn't work.
I tried going to the page on my phone, nothing.

Device: iPhone SE (1st gen)
iOS: 14.4
Jailbreak: Checkra1n
SMServer version (libmserver is including with SMServer now so I can't get that version): 0.8.0
Installed deb with zebra

**Comment by nab138** [comment]
Update: Tried smcurser and it works fine with that.

I have no idea why it doesn't work on the browser

**Comment by nab138** [comment]
Tried on chrome and firefox, firefox loads infinitely rather then saying "This page isnt working" like chrome did

**Comment by nab138** [comment]
#41 Disabling SSL and using HTTP worked for me

**Comment by iandwelker** [comment]
@nab138 I suspect your issue was simply that you didn't specify `https` when typing in the address. Most browsers default to `http` connections when you simply type an address into the URL Bar, and SMServer doesn't accept http connections when you are running the secure server. If you enable SSL and then visit `https://192.168.1.210:8741` (notice the `s`), I expect it will work fine.
