### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by 22350** [iandwelker/smserver#140]
Hi everyone.  lost my phone so had to set up an iphone 7

I am jailbroken with checkrain on 14.6

I have tried to install 0.8.0 on altstore , itools,  and from a cycdia repo.  nothing works.

any ideas?

**Comment by h4x1nC** [comment]
There is not worked

**Comment by 22350** [comment]
> There is not worked

I’m not sure what you are saying

**Comment by 22350** [comment]
Not sure what changed, but I was able to install it from a Cydia repo

**Comment by iandwelker** [comment]
Sorry about the late response - Could you check to make sure you have the tweak `libmryipc` installed on your phone? If you don't, install it, `ldrestart`, and try SMServer again.

**Comment by 22350** [comment]
> Sorry about the late response - Could you check to make sure you have the tweak `libmryipc` installed on your phone? If you don't, install it, `ldrestart`, and try SMServer again.

that solved it. thanks

**Comment by 22350** [comment]
> > Sorry about the late response - Could you check to make sure you have the tweak `libmryipc` installed on your phone? If you don't, install it, `ldrestart`, and try SMServer again.
> 
> In stalled Libmryipc and then re-jailbroke phone. Now smserver starts, but when i try to hit the "play" arrow, is quits again.

Update.  installed libsmserver and libmryipc and then uninstalled smserver and reinstalled.  now works.
