### ISSUE TITLE
Style problems on Opera GX and iOS Safari

### ISSUE THREAD

**Issue by symbuzzer** [iandwelker/smserver#15]
Style problems on Opera GX and iOS Safari

**Comment by iandwelker** [comment]
Could you attach an image to show the issues?

**Comment by dudeamax99** [comment]
I think this is what they mean. Some profile pictures were blacked out by me, none of the chats were however. ![9DC46379-A1F6-4CE2-95A9-3A13A0DA669D](https://user-images.githubusercontent.com/46611144/90707312-5393f080-e265-11ea-83f6-3ff6342360a1.jpeg)

**Comment by iandwelker** [comment]
Ah, gotcha. I don't use safari much, so I didn't notice it. I'll check it out and update when I've got it fixed, though.

**Comment by iandwelker** [comment]
Sorry this issue has been stale for so long, but I have an update now: These issues should be fixed in the next version. Once that's uploaded, if this issue appears fixed, I'll close the issue.

**Comment by iandwelker** [comment]
These issues should be fixed now in version 0.3.6. Could y'all try it out and let me know if the issues appear fixed for you?

**Comment by iandwelker** [comment]
Issue has been stale for a few days. These issues have been fixed as far as I've been able to tell, so I'm closing this. Feel free to reopen it if these issues are not fixed for you.
