### ISSUE TITLE
App crashes on server launch

### ISSUE THREAD

**Issue by clarsen32** [iandwelker/smserver#22]
Device model: iPhone 7
Jailbreak (e.g. checkra1n, unc0ver, Chimera, etc): odysseyra1n via checkra1n 0.10.2
iOS Version: 13.6.1
How you installed the app: Sileo
SMServer version: 0.3.4

App closes when the "play" or "reload" buttons are pressed on the bottom toolbar of the app. Rest of the app works fine, just goes into safe mode when you try to start the server. In addition, the Messages app crashes on launch, although push notifications still appear for new texts and you can reply using the quick reply from the notifications.

Tried downgrading both SMServer and libsmserver and disabled all other tweaks. No luck yet.

**Comment by iandwelker** [comment]
I've just noticed there's been an update to libmryipc, which is utilized by this app, and there are reports of it crashing other apps/tweaks. If you downgrade libmryipc to the latest before 2.0, do things start working again?

**Comment by clarsen32** [comment]
I tried to downgrade but wasn't able to through either Sileo or ios-repo-updates. But if there are reports of it crashing other tweaks today after it got updated this morning I would say it's a good possibility that's what is causing the issues.

**Comment by iandwelker** [comment]
So I found what the issue was, it's due a change in the way libMRYIPC works in this new update. I'll push a fix to libsmserver soon which should resolve this issue, so look out for that.

**Comment by iandwelker** [comment]
I've updated libsmserver to 0.2.2, and it should fix the crash. Once that version is available to you, could you update to it and let me know if it fixes the issue for you?

**Comment by jiznon** [comment]
Not OP, but experiencing same issue. Updated to libsmserver 0.2.2-2+debug but SMServer still scrashes on pressing Play. Also Cydia is letting me know there is a SMServer update to 0.3.4 but that's the version installed. I'm guessing this is a repo issue.

**Comment by iandwelker** [comment]
@jiznon Yeah, you're right. 0.2.2 is broken; I fixed the issues, tested it, and updated the package to 0.2.3. Could you test that out and let me know?

And yes, I'm fairly certain that's a repo issue; I have yet to find the reason for that. I'll try to talk to people at twickd to get that fixed.

**Comment by clarsen32** [comment]
With 0.2.3 it loads just fine but it looks like I'm missing some chats? Not sure if that's just me

**Comment by iandwelker** [comment]
I'm glad it seems to be loading fine; if you're missing some chats in the web interface, though, that would be a separate issue. I'd be glad to look into that if you open up another issue here with more detail about exactly what you're running into.
