### ISSUE TITLE
Causing safe mode on Iphone X 13.4.1

### ISSUE THREAD

**Issue by hello-there-young-fellow** [iandwelker/smserver#23]
tweak installs and opens fine. upon clicking the start button, my phone always goes into safe mode. jailbroken with unc0ver and newest version of smserver installed.

**Comment by iandwelker** [comment]
Yes, I've had a few other reports of this; it's due to an update in libmryipc, which this app utilizes. I'll push an update to libsmserver soon which should fix this, but in the meantime you should just be able to downgrade libMRYIPC to 1.0.

**Comment by iandwelker** [comment]
I've pushed the update to libsmserver (it's now version 0.2.2). Once it becomes available, could you install the update and let me know if it fixes the issue for you?

**Comment by shanep2300** [comment]
On 0.3.0 and no more safe mode with updated libM.

**Comment by hello-there-young-fellow** [comment]
great. nice to see devs actively maintaining their tweaks!

**Comment by iandwelker** [comment]
Glad everything is working. I'll close this.

**Comment by hello-there-young-fellow** [comment]
that didnt take you long to reply

**Comment by hello-there-young-fellow** [comment]
aaaaand that didn't last long, now app crashes when attempting to open up a message stream on the computer side :(

**Comment by iandwelker** [comment]
what do you mean by 'open up a message stream'?

**Comment by shanep2300** [comment]
Yup, this is happening to me as well just now. But technically the safe mode issue is fixed :P

App is now crashing when I receive a message. If I do an ldrestart or restart userspace, it's back to normal. It works in background I can see messages etc. But as soon as someone sends me a text, it crashes. Can't restart the server and the app crashes when I try to start it.

**Comment by hello-there-young-fellow** [comment]
I mean on the computer side, when I click a conversation to write a message, the app crashes and the server dies.

**Comment by iandwelker** [comment]
Would you both be able to get me a log, as described in the README under `To file an issue:`, the section that starts with "Also, if the app did not crash on startup..."?

**Comment by hello-there-young-fellow** [comment]
sure, Itll take a bit because I already downgraded, lol

**Comment by hello-there-young-fellow** [comment]
hm, its not happening anymore

**Comment by hello-there-young-fellow** [comment]
funny, it crashed but theres nothing in the log

**Comment by iandwelker** [comment]
If you disable the "mark as read" toggle in settings & restart the app, do you run into the issue anymore?

**Comment by iandwelker** [comment]
Another user was reporting something similar and said that this was fixed in version 0.3.6. Could you try that out and let me know if it fixed it for you as well?

**Comment by iandwelker** [comment]
Issue has been stale for a bit; other users are reporting that this issue was fixed in the 0.3.6 update, so I'm closing this for now. Feel free to reopen if the issue was not fixed.
