### ISSUE TITLE
Server loads forever

### ISSUE THREAD

**Issue by justin0386** [iandwelker/smserver#30]
I recently just updated my phone to iOS 13.6.1 which may of caused this as it was working before. Every time I hit the arrow button to start the server it starts but when I go to the link it just loads and loads and loads and doesn't do anything. I am also on a iPhone 8+. Also using the checkra1n jb and using the latest version of the tweak.

**Comment by iandwelker** [comment]
Sometimes this happens to me, but an ldrestart with airplane mode turned on normally fixes it. Have you tried anything like that yet?

**Comment by justin0386** [comment]
I have not. I am currently trying to find a tweak to do a ldrestart. Do you know of one? I tried Powerselector but its not working.

**Comment by iandwelker** [comment]
I personally use Powerselector; I know that PowerApp works well too, maybe try that.

**Comment by justin0386** [comment]
I downloaded powerapp and the options are,reboot,shutdown,soft reboot,respring,safe mode,non-substrate mode,refresh cache,then exit. I read that the soft reboot is the ldrestart from what I read and I gave it a try and still did not work.

**Comment by iandwelker** [comment]
I guess then we should just check a few basic things:
1. Are you connecting to the right address with regards to `http://` vs `https://` at the beginning?
1. Is your host device connected to the same wifi/wlan network as your client device?
1. Have you blocked connections in/out from SMServer via another tweak?
1. Are you using a vpn while trying to use the server?

**Comment by Magicalrudedude** [comment]
Server just loads forever and says it can't connect to the server on my browser.

**Comment by justin0386** [comment]
I figured my problem out it was the antivirus but now there is a diff issue. whenever I run the server it connects to the server but when I click a message on the server the app just crashes.

**Comment by iandwelker** [comment]
@justin0386 What do you mean by message? A conversation, perhaps?

@Magicalrudedude did you already try the steps and check all the things mentioned above?

**Comment by justin0386** [comment]
Yeah whenever I click on a conversation the SMServer app just crashes and the server freezes up.

**Comment by justin0386** [comment]
I figured it out I had to turn off the messages marked as read and now its working.
