### ISSUE TITLE
Can't see my replies on group messages

### ISSUE THREAD

**Issue by shanep2300** [iandwelker/smserver#34]
When its a conversation between me and one person, all texts including mine load fine (whether it's iMessage or Text)

Group messages (whether it's iMessage or Text) load all messages but mine.

**Comment by iandwelker** [comment]
Yup, I just realized I see this issue too; thanks for bringing it up. I'll update this once I find the fix

**Comment by iandwelker** [comment]
Found the issue. I used an inner join on line 269 of `ChatDelegate.swift` when I should've used a left join. I'll try to push out an update soon to fix this.

**Comment by iandwelker** [comment]
Sorry the update is a bit late; it's been submitted to Twickd now, though, so try it out when it becomes available and let me know if it fixed the issue for you as well.

**Comment by shanep2300** [comment]
Don't be sorry! I really appreciate the work you're putting into this and the quick responses into bug fixes/requests!

As for the fix, it's working!
