### ISSUE TITLE
Web interface cant receive messages or view contacts on the side

### ISSUE THREAD

**Issue by antargame** [iandwelker/smserver#40]
Iphone xr
unc0ver
13.2.3
twickd repo
the web interface has nothing on it, i can send messages but cant recieve or view my contacts. 
SMServer: 0.4.3
Libsmsesrver: 0.3.5
![2020-09-21 (5)](https://user-images.githubusercontent.com/71662501/93800854-30b37e00-fc0f-11ea-9efa-55db9d8cdcb4.png)

**Comment by iandwelker** [comment]
Were you able to view your conversations before the most recent update? Also, if you check your browser's console, does it show any errors?

**Comment by antargame** [comment]
this is the first time i am using this, i tried version 0.4.2 and 0.4.1 and same problem

**Comment by antargame** [comment]
ill check the console

**Comment by iandwelker** [comment]
Are you possibly using an outdated version of unc0ver? That's been causing similar issues for other users.

**Comment by antargame** [comment]
unc0ver version 4.3.1 also how do i check the console for the browser?

**Comment by iandwelker** [comment]
I think your issue is with unc0ver. I'd recommend updating to the latest available version of unc0ver; I'm fairly certain that will fix your issue. If you'd like to check the browser console, right click on the window, hit 'inspect element', then click on the 'console' tab of the section that pops up

**Comment by antargame** [comment]
Uncaught (in promise) TypeError: Cannot read property 'chat_identifier' of undefined
    at getChatElement ((index):205)
    at setChatAsTop ((index):819)

**Comment by iandwelker** [comment]
Yeah, so that means that the API backend isn't returning anything, so it doesn't have anything to print. With everyone else who's had the same issue (see issues #7, #8, and #10), updating unc0ver has been the fix.

**Comment by antargame** [comment]
i updated unc0ver nothing changed. its the same ios but its version 5.3.1 unc0ver

**Comment by antargame** [comment]
And i just tested it again and didnt get anything in the console

**Comment by iandwelker** [comment]
Did you reinstall the app after updating unc0ver? If you haven't, do so. If that still doesn't fix the issue, then authenticate with the web interface and visit the link that shows in the main interface of the app, but with `/requests?chat=0` appended onto it (the final link will look something like `https://192.168.0.127:8741/requests?chat=0`). Let me know what shows on that link.

**Comment by antargame** [comment]
yes i reinstalled the app still the same issue.
{ "chats": [

]
}

**Comment by antargame** [comment]
wait i didnt reinstall libsmserver, let me try that

**Comment by iandwelker** [comment]
On the readme of this repo, underneath the section that says 'Also, if the app did not crash on startup, ...' there are instructions on how to get a log from the app. Could you run through those steps and attach the log so that I can look through it?

**Comment by antargame** [comment]
ok

**Comment by antargame** [comment]
what should i use to ssh into my phone?

**Comment by iandwelker** [comment]
If you're on windows, you can use command prompt (just open a command prompt and run `ssh root@YOUR_DEVICE_IP`, replacing YOUR_DEVICE_IP with your device's IP), on Mac you can use terminal, and on linux you can just use whatever terminal emulator you normally use

**Comment by antargame** [comment]
ah ok i didnt know i could do it on windows

**Comment by antargame** [comment]
yeah so im getting the same problem as i did on linux connection refused/timed out

**Comment by antargame** [comment]
im using openssh and getting permission denied even though im putting the right password

**Comment by antargame** [comment]
disregard my past comments i messed something but it works now

**Comment by antargame** [comment]
iPhone SMServer(com.ianwelker.smserver.debugging)[8047] <Debug>: SMServer_app: Could not load custom css file

**Comment by antargame** [comment]
i dont think this is a problem with unc0ver since it still didnt work after updating

**Comment by iandwelker** [comment]
> iPhone SMServer(com.ianwelker.smserver.debugging)[8047] : SMServer_app: Could not load custom css file

Is this comment above all the log that you were able to get? It should be significantly longer than that if you did everything correctly.

**Comment by antargame** [comment]
thats all i got. i sshed into my phone with root then put in the command that you had posted

**Comment by antargame** [comment]
after i installed the latest version of unc0ver and rejailbreaked

**Comment by antargame** [comment]
bump

**Comment by iandwelker** [comment]
Please just trust that I'm working on this. It's been barely 10 hours since I last responded, and I have school, a job, and other projects to work on before I can get back to this. I'd appreciate it if you can give me time to work on this before updating the issue.

**Comment by antargame** [comment]
wait i have more stuff
i just put the bump to bump you 
Sep 22 20:42:34 iPhone SMServer(com.ianwelker.smserver.debugging)[16281] <Debug>: SMServer_app: Could not load custom css file
Sep 22 20:42:38 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Could not load custom css file
Sep 22 20:42:40 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Loading server at port 8741
Sep 22 20:42:40 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: launched MobileSMS
Sep 22 20:42:40 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Got past adding all the handlers.
Sep 22 20:42:40 iPhone SpringBoard[5741] <Notice>: LibSMServer_app: called LaunchSMS
Sep 22 20:42:40 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Started websocket successfully.
Sep 22 20:42:40 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Successfully started server and launched MobileSMS
Sep 22 20:42:48 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: GET main: 10.0.0.59
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Getting requests..
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: GET /requests: 10.0.0.59Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: parsing password and Optional("toor")
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: comparing toor to toor
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Returning from /requestsSep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: GET main: 10.0.0.59
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: GET style: 10.0.0.59
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: GET style: 10.0.0.59
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: GET style: 10.0.0.59
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Getting requests..
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: GET /requests: 10.0.0.59Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: parsing num_chats and Optional("60")
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: parsing chats_offset and Optional("0")
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: parsing chat and Optional("0")
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: num chats: 60
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: chats offset: 0
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Getting chats
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: WARNING: error opening database at /private/var/mobile/Library/SMS/sms.db: 14
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: opened database
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Returning from /requestsSep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: 10.0.0.59 is trying to connect...
Sep 22 20:42:51 iPhone SMServer(com.ianwelker.smserver.debugging)[16300] <Debug>: SMServer_app: Received message: 9 bytes

**Comment by iandwelker** [comment]
So it appears that your phone just can't access the `sms.db` on your phone. Do you think you could ssh into your phone, run the command `ls -la /private/var/mobile/Library/SMS/sms.db`, and paste the output from it here?

**Comment by antargame** [comment]
it says operation not permitted

**Comment by antargame** [comment]
ls: cannot access '/private/var/mobile/Library/SMS/sms.db': Operation not permitted

**Comment by iandwelker** [comment]
What happens if you try to `ls -la` each folder above it (e.g. `ls -la /private/var/mobile/Library/SMS`, `ls -la /private/var/mobile/Library`, etc...). Also, what does it output if you run `whoami`?

**Comment by iandwelker** [comment]
This issue has not seen a response from its creator for more than 2 months, so I'll be closing it. If you are still running into this issue, feel free to reopen it with more details.

**Comment by ffaen** [comment]
I am having a similar issue running:

* iOS 13.5
* unc0ver 5.3.1 (after upgrading from 5.0.0)
* SMServer 0.6.0 (with dependencies installed) 

It seems to be that I cannot access the SMS folder, I can view everything else...

```
$ whoami

root
```

```
$ ls -la /private/var/mobile/Library

ls: cannot access 'ExposureNotification': Operation not permitted
ls: cannot access 'Trial': Operation not permitted
ls: cannot access 'CallHistoryDB': Operation not permitted
ls: cannot access 'IdentityServices': Operation not permitted
ls: cannot access 'Voicemail': Operation not permitted
ls: cannot access 'Shortcuts': Operation not permitted
ls: cannot access 'TCC': Operation not permitted
ls: cannot access 'VoiceShortcuts': Operation not permitted
ls: cannot access 'dmd': Operation not permitted
ls: cannot access 'DuetExpertCenter': Operation not permitted
ls: cannot access 'Mail': Operation not permitted
ls: cannot access 'Safari': Operation not permitted
ls: cannot access 'coreidvd': Operation not permitted
ls: cannot access 'com.apple.nsurlsessiond': Operation not permitted
ls: cannot access 'com.apple.internal.ck': Operation not permitted
ls: cannot access 'com.apple.sensorkitd': Operation not permitted
ls: cannot access 'Health': Operation not permitted
ls: cannot access 'Notes': Operation not permitted
ls: cannot access 'CallHistoryTransactions': Operation not permitted
ls: cannot access 'com.apple.siri.inference': Operation not permitted
ls: cannot access 'SMS': Operation not permitted
total 0
drwx--x--x 148 mobile mobile           4736 Nov 28 18:21 ./
drwx--x--x  12 mobile mobile            384 Nov  6 01:06 ../
drwxr-xr-x   9 mobile mobile            288 Dec  8  2019 Accessibility/
drwx------   6 mobile mobile            192 Nov  3 22:32 Accounts/
drwx------  10 mobile mobile            320 Dec  5  2019 AddressBook/
drwxr-xr-x   8 mobile mobile            256 Nov 28 18:32 AggregateDictionary/
drwxr-xr-x   3 mobile mobile             96 Nov 27 22:03 AirPlayRoutePrediction/
drwxr-xr-x   4 mobile mobile            128 Nov 28 18:30 AppConduit/
drwxr-xr-x   5 mobile mobile            160 Dec  8  2019 ApplePushService/
drwxr-xr-x  23 mobile mobile            736 Jun 11 23:05 Application\ Support/
drwxr-xr-x   4 mobile mobile            128 Dec  8  2019 ApplicationSync/
drwxr-xr-x   2 root   mobile             64 Dec  8  2019 Assets/
drwxr-xr-x  21 mobile mobile            672 Nov 28 18:33 Assistant/
drwxr-xr-x   4 mobile mobile            128 May 22  2020 Avatar/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 BackBoard/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 Backup/
drwxr-xr-x   5 mobile mobile            160 Nov 28 18:29 BulletinBoard/
drwxrwxrwx 148 mobile mobile           4736 Nov 28 18:31 Caches/
drwx------  14 mobile mobile            448 Nov 26 23:49 Calendar/
drwxr-xr-x   3 mobile mobile             96 Nov 28 05:00 CallDirectory/
d?????????   ? ?      ?                   ?            ? CallHistoryDB/
d?????????   ? ?      ?                   ?            ? CallHistoryTransactions/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 CallServices/
lrwxr-xr-x   1 mobile mobile             44 May 29  2020 Carrier\ Bundle.bundle -> /System/Library/Carrier\ Bundles/iPhone/23420/
drwxr-xr-x   4 mobile mobile            128 Sep 26 01:14 Carrier\ Bundles/
lrwxr-xr-x   1 mobile mobile             44 May 29  2020 Carrier1Bundle.bundle -> /System/Library/Carrier\ Bundles/iPhone/23420/
lrwxr-xr-x   1 mobile mobile             53 May 21  2020 CarrierDefault.bundle -> /System/Library/Carrier\ Bundles/iPhone/Default.bundle/
drwxr-xr-x   5 mobile mobile            160 Nov 28 18:24 ClassKit/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 Contacts/
drwxr-xr-x   6 mobile mobile            192 Mar  9  2020 ContactsMetadata/
drwxr-xr-x   3 mobile mobile             96 Mar  7  2020 ControlCenter/
drwx------  22 mobile mobile            704 Nov 28 18:33 Cookies/
drwxr-xr-x   7 mobile mobile            224 May 21  2020 CoreAS/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 CoreAccessories/
drwxr-xr-x   5 mobile mobile            160 Dec  9  2019 CoreBehavior/
drwxr-xr-x   5 mobile mobile            160 Dec  8  2019 CoreBrightness/
drwxr-xr-x   5 mobile mobile            160 May 21  2020 CoreDuet/
drwxr-xr-x   3 mobile mobile             96 Nov 25 20:11 CoreFollowUp/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 CrashReporter/
drwxr-xr-x   3 mobile mobile             96 May 23  2020 Cydia/
drwxr-xr-x   5 mobile mobile            160 Dec 17  2019 DES/
drwxr-xr-x   8 mobile mobile            256 Nov 28 18:21 DataAccess/
drwxr-xr-x   3 mobile mobile             96 Nov 21 00:32 DeviceRegistry/
drwxr-xr-x   3 mobile mobile             96 Nov 28 18:21 DeviceRegistry.dontBackUp/
drwxr-xr-x  13 mobile mobile            416 Nov 28 18:21 DeviceRegistry.state/
drwxr-xr-x   6 mobile mobile            192 Dec  8  2019 DifferentialPrivacy/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 DoNotDisturb/
drwxr-xr-x   6 mobile mobile            192 Jan  2  2020 DuetActivityScheduler/
d?????????   ? ?      ?                   ?            ? DuetExpertCenter/
d?????????   ? ?      ?                   ?            ? ExposureNotification/
drwxr-xr-x 710 mobile mobile          22720 Aug 15 08:37 ExternalAccessory/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 FairPlay/
drwxr-xr-x   7 mobile mobile            224 Dec  8  2019 FileProvider/
drwxr-xr-x   5 mobile mobile            160 Dec  8  2019 FrontBoard/
drwx--x--x   2 mobile mobile             64 Dec  8  2019 GameKit/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 GeoServices/
d?????????   ? ?      ?                   ?            ? Health/
drwxrwxrwx   4 mobile mobile            128 Nov 28 18:25 ISP/
d?????????   ? ?      ?                   ?            ? IdentityServices/
drwxr-xr-x   2 mobile mobile             64 Dec  5  2019 Inboxes/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 Intents/
drwx------  29 mobile mobile            928 Nov 28 18:31 Keyboard/
drwxr-xr-x   5 mobile mobile            160 Dec  8  2019 KeyboardServices/
drwxr-xr-x   6 mobile mobile            192 Nov 28 18:21 LASD/
drwxrwx---   3 mobile _analyticsusers    96 Dec  8  2019 Library/
drwxrwxr-x  16 mobile _analyticsusers   512 Nov 28 00:15 Logs/
d?????????   ? ?      ?                   ?            ? Mail/
drwxr-xr-x   2 mobile mobile             64 Jul 20 23:15 Measure/
drwxr-xr-x   3 mobile mobile             96 Feb 16  2020 MediaRemote/
drwxr-xr-x   9 mobile mobile            288 Dec  8  2019 MediaStream/
drwxr-xr-x   3 mobile mobile             96 Sep  2 14:50 MedicalID/
drwxrwxrwx   3 mobile mobile             96 Dec  8  2019 MessagesMetaData/
drwxr-xr-x  76 mobile mobile           2432 Nov 10 18:52 Mobile\ Documents/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 MobileBluetooth/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 MobileContainerManager/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 MobileInstallation/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 MusicLibrary/
drwxr-xr-x   5 mobile mobile            160 Dec  8  2019 NFStorage/
drwxr-xr-x  11 mobile mobile            352 Nov 20 19:26 NanoBackup/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 NanoMusicSync/
drwxr-xr-x   2 mobile mobile             64 Nov 28 18:22 NanoPhotos/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 NanoPreferencesSync/
drwxr-xr-x   5 mobile mobile            160 Dec  8  2019 NanoTimeKit/
drwxr-xr-x   4 mobile mobile            128 May 25  2020 News/
d?????????   ? ?      ?                   ?            ? Notes/
drwxrwx---   4 mobile _analyticsusers   128 Dec  8  2019 OSAnalytics/
drwxrwxrwx   3 root   mobile             96 Dec  8  2019 OTALogging/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 OnDemandResources/
lrwxr-xr-x   1 mobile mobile             44 Nov 27 17:06 Operator\ Bundle.bundle -> /System/Library/Carrier\ Bundles/iPhone/23420/
lrwxr-xr-x   1 mobile mobile             44 Nov 27 17:06 Operator1Bundle.bundle -> /System/Library/Carrier\ Bundles/iPhone/23420/
drwxr-xr-x  19 mobile mobile            608 Nov 28 18:31 Passes/
drwxr-xr-x   8 mobile mobile            256 Dec  8  2019 PersonalizationPortrait/
drwxr-xr-x   4 mobile mobile            128 Nov 28 18:21 PowerUI/
drwxr-xr-x 599 mobile mobile          19168 Nov 28 18:33 Preferences/
drwx------   5 mobile mobile            160 Dec  8  2019 Recents/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 RelevanceEngine/
drwxr-xr-x   4 mobile mobile            128 Dec  8  2019 Reminders/
drwx--x--x   2 mobile mobile             64 Nov  8 05:44 ReplayKit/
drwxr-xr-x   4 mobile mobile            128 Apr 19  2020 ResponseKit/
d?????????   ? ?      ?                   ?            ? SMS/
d?????????   ? ?      ?                   ?            ? Safari/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 SafariSafeBrowsing/
drwxr-xr-x  18 mobile mobile            576 Nov 28 18:08 Saved\ Application\ State/
drwxr-xr-x   5 mobile mobile            160 May 21  2020 SecureElementService/
drwxr-xr-x   5 mobile mobile            160 Sep  2 19:02 Sharing/
d?????????   ? ?      ?                   ?            ? Shortcuts/
drwxr-xr-x   5 mobile mobile            160 Nov 28 01:24 Snapper2/
drwxr-xr-x   3 mobile mobile             96 May 21  2020 SoftwareUpdate/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 SplashBoard/
drwxr-xr-x  13 mobile mobile            416 Nov 28 17:26 Spotlight/
drwxr-xr-x  40 mobile mobile           1280 Nov 28 18:33 SpringBoard/
drwxr-xr-x  27 mobile mobile            864 Nov 25 08:38 Suggestions/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 SyncedIntentDefinitions/
drwxr-xr-x  33 mobile mobile           1056 Nov 28 18:32 SyncedPreferences/
d?????????   ? ?      ?                   ?            ? TCC/
d?????????   ? ?      ?                   ?            ? Trial/
drwxr-xr-x   9 mobile mobile            288 Nov 28 18:28 UserConfigurationProfiles/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 UserFonts/
drwxr-xr-x 226 mobile mobile           7232 Nov 24 16:17 UserNotifications/
drwxr-xr-x   3 mobile mobile             96 Nov 28 18:08 UserNotificationsServer/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 VoiceServices/
d?????????   ? ?      ?                   ?            ? VoiceShortcuts/
drwxr-xr-x   4 mobile mobile            128 Dec 11  2019 VoiceTrigger/
d?????????   ? ?      ?                   ?            ? Voicemail/
drwxr-xr-x   3 mobile mobile             96 Dec  8  2019 WatchConnectivity/
drwx------  10 mobile mobile            320 Nov 10 13:15 WebClips/
drwxr-xr-x   6 mobile mobile            192 Oct  1 14:08 WebKit/
drwxr-xr-x   3 mobile mobile             96 Nov 28 18:21 WelcomeMat/
drwxr-xr-x   2 root   mobile             64 Dec  8  2019 YouTube/
drwxr-xr-x   6 mobile mobile            192 Oct 25 17:27 com.apple.VideoSubscriberAccount.DeveloperService/
drwxr-xr-x   5 mobile mobile            160 Nov  2 16:52 com.apple.WatchListKit/
drwxr-xr-x   3 mobile mobile             96 Nov  7 15:31 com.apple.assistant.Contacts/
drwxr-xr-x   2 mobile mobile             64 Dec  8  2019 com.apple.companionappd/
drwxr-xr-x   5 mobile mobile            160 Dec  8  2019 com.apple.iTunesCloud/
drwxrwx---  13 mobile mobile            416 Nov 28 18:21 com.apple.icloud.searchpartyd/
d?????????   ? ?      ?                   ?            ? com.apple.internal.ck/
drwxr-xr-x  20 mobile mobile            640 Nov 28 18:21 com.apple.itunesstored/
d?????????   ? ?      ?                   ?            ? com.apple.nsurlsessiond/
drwxr-xr-x   3 mobile mobile             96 Nov 28 18:32 com.apple.nsurlsessiond-launchd/
drwx------   2 mobile mobile             64 Jan 27  2020 com.apple.printd/
d?????????   ? ?      ?                   ?            ? com.apple.sensorkitd/
d?????????   ? ?      ?                   ?            ? com.apple.siri.inference/
d?????????   ? ?      ?                   ?            ? coreidvd/
d?????????   ? ?      ?                   ?            ? dmd/
drwx------  17 mobile mobile            544 Nov 28 18:21 homed/
drwx------   3 root   wheel              96 Nov 27 08:06 locationd/
drwx------   3 mobile mobile             96 Dec  8  2019 mad/
drwxr-xr-x   5 mobile mobile            160 Nov 20 23:06 terminus/
```

Thank you for your work on this, it seems super useful once I can get it up and running :)

**Comment by iandwelker** [comment]
It appears that a significant amount of the folders in that parent folder (`/private/var/mobile/Library`) have messed up permissions (as you can see with the many question marks), so I don't think there's much that I can do to remedy that. I'd recommend (if possible) backing up your tweaks, running a rootfs restore, then re-jailbreaking and trying again. That may fix your permissions issues and allow SMServer to work correctly.

**Comment by ffaen** [comment]
This has got it, not sure what managed to do that but a rootfs and reinstall seems to have cracked it. Thank you! ⭐

**Comment by iandwelker** [comment]
Glad to hear that :) I'll close the issue
