### ISSUE TITLE
iOS 14.0.1 

### ISSUE THREAD

**Issue by ikey-ru** [iandwelker/smserver#47]
Sending messages via the browser doesn't work. :(

**Comment by iandwelker** [comment]
Yes, unfortunately iOS 14 did break some parts of SMServer. However, I've been working hard on rewriting the sections that were affected by iOS 14 (it's been 1500 lines of code so far that I've changed/added/removed) and I have basically everything working now. I still have to fix sending attachments/images, but once I've figured that out, I'll release an update with full support for iOS 14.

**Comment by ikey-ru** [comment]
Your answer made me very happy, thank you!

**Comment by iandwelker** [comment]
An update: I think I'll be able to release support for iOS 14 within the next few days. I'm just waiting on confirmation that it still works with iOS 13 before I officially release it.

**Comment by ikey-ru** [comment]
That'll be great, and I look forward)

**Comment by iandwelker** [comment]
alright, the new version is out now (0.5.0) and should fix this issue; I'll close the issue and feel free to reopen it if you're still running into the same thing.
