### ISSUE TITLE
Websocket pop up

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#49]
![websocket](https://user-images.githubusercontent.com/53708281/97743316-dafaad00-1abb-11eb-8c4c-7de997ccbaf3.JPG)
I get a pop up to trust the websocket whether I'm on http or https. I had it set at the default 8740 but attempted to change it to see if I would be able to trust it. I get this pop up every time I open the client, however as far as I can tell, the functionality isn't affected. Is this pop up anything to worry about/can it be disabled?

**Comment by iandwelker** [comment]
As long as functionality seems unaffected, you should be fine. However, I'd like to verify first that functionality actually isn't impacted: When you load up the web page, does the battery percentage show as 0% or the actual percentage? If it shows as 0 or is empty, then the websocket is actually not working.
Also, what browser are you using? And have you visited the address stated in that alert and trusted the certificate that appears there?

**Comment by CSab6482** [comment]
I am using the Brave browser, and since I am not getting battery percentage/sometimes my messages aren't updated I suspect the web socket is in fact not working. I've navigated to the address in the alert and each time it just loads for a long time then gives me this screen
![No websocket](https://user-images.githubusercontent.com/53708281/97744609-ed75e600-1abd-11eb-9ffb-a571335416aa.png)
I thought perhaps it was an https vs http problem but changing that didn't work, and neither did restoring the default values. I will attempt to restore the default values again and try my luck in FireFox and Edge

**Comment by CSab6482** [comment]
I was able to fix the issue. When port forwarding I needed to forward both the server port and the websocket port over TCP. No further pop up or problems, thanks so much.
