### ISSUE TITLE
Battery percentage not working for me as of version 0.5.2

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#50]
![0 battery](https://user-images.githubusercontent.com/53708281/97743505-244afc80-1abc-11eb-8fd0-e8970b2f89ca.jpg)
Is there any way to downgrade the app to see if this is a version problem? Previously, I had the server running on my internal IP and port as well as a DDNS address and the forwarded port. The battery would show up on the internal IP version but not on the DDNS version. Now it isn't present on either.

**Comment by CSab6482** [comment]
Apologies for not specifying my device and jailbreak previosuly.
iPhone 6S
iOS 14.1
checkra1n / odysseyra1n
Sileo
SMServer 0.5.2, libsmserver 0.4.0

**Comment by iandwelker** [comment]
this is related to your other issue (with the websocket popup) -- it appears the websocket is not actually connecting, so the battery percentage doesn't update. If it's ok with you, let's close this one and only communicate on the other one.

**Comment by CSab6482** [comment]
Perfect. Thank you for the quick response!
