### ISSUE TITLE
How to sent a request using curl?

### ISSUE THREAD

**Issue by RazrFalcon** [iandwelker/smserver#52]
Hi, I'm trying to sent a `send` request via curl, but it either does nothing or crashes the server:

```
> curl "http://IP:8741/requests?password=toor"
true
> curl "http://IP:8741/send?subject=subj&text=text&chat=PHONE"
curl: (52) Empty reply from server
> curl -v "http://IP:8741/send?subject=subj&text=text&chat=PHONE"
*   Trying IP:8741...
* connect to IP port 8741 failed: Connection refused
* Failed to connect to IP port 8741: Connection refused
* Closing connection 0
curl: (7) Failed to connect to IP port 8741: Connection refused
```

IP and PHONE are just placeholders for this issue, I'm using an actual IP and a phone.

iOS 13.3.1,  SMServer 0.5.2

Web interface works just fine.

**Comment by iandwelker** [comment]
Your issues is that you're sending these requests as `GET` requests, as opposed to `POST` requests. When you send requests to the `/data` or `/requests` subdirectory, they should be sent as `GET` (as shown in your first request), but requests sent to `/send` have to be sent as `POST`. For example, to do what you're trying to do, you'd have to run:
```bash
curl -X POST -k -d "subject=subj&text=text&chat=PHONE" "http://IP:8471/send"
```
The `-k` flag is unnecessary if you're just using http, but if you use https, it will be necessary to bypass the self-signed cert error.

**Comment by RazrFalcon** [comment]
Oh, you're sending the data as POST data and not as URL query. This was my mistake. Thanks.
