### ISSUE TITLE
Issuing troubles while trying to send sms via API

### ISSUE THREAD

**Issue by ikey-ru** [iandwelker/smserver#53]
Hi!
I'm trying to send SMS via your API, but facing some troubles. When I'm trying to authenticate - all ok, I'm getting code 200 response with content body "true", however send sms POST request returns "false" body and nothing happens. Here's my code snippet:
```kotlin
fun main(vararg params: String) {
    val baseUrl = "http://192.168.1.23:8741"

    val client = HttpClient.newHttpClient()
    val authRequest = HttpRequest.newBuilder()
            .uri(URI.create("$baseUrl/requests?password=toor"))
            .build()

    val authResponse = client.send(authRequest, HttpResponse.BodyHandlers.ofString())
    println("Auth Code is ${authResponse.statusCode()}")
    println("Auth Data is ${authResponse.body()}")

    val postValues = "text=hello&chat=+79516497228"
    val sendRequest = HttpRequest.newBuilder(URI.create("$baseUrl/send"))
            .POST(HttpRequest.BodyPublishers.ofString(postValues))
            .build()

    val sendResponse = client.send(sendRequest, HttpResponse.BodyHandlers.ofString())
    println("Code is ${sendResponse.statusCode()}")
    println("Data is ${sendResponse.body()}")

}
```

And output is: 
`Auth Code is 200
Auth Data is true
Code is 200
Data is false`

**Comment by iandwelker** [comment]
When sending a text through SMServer, it only returns "false" when you have no content in your text, meaning that the "text" & "subject" parameters are empty, and you attached no attachments, so I'd guess that your post values is where the fault lies. I haven't used Java before, but I did some poking around and it looks like you may need to place your post values in a Hash Map as opposed to a plain string &mdash; [this site](http://zetcode.com/java/getpostrequest/) seems to have good information that may help you.

**Comment by ikey-ru** [comment]
Hi! In that example HashMap used to accumulate some values that should be serialized to json. To fix this problem I had to define explicitly content type header (application/x-www-form-urlencoded), after that all works good.
