### ISSUE TITLE
14.1 crashing

### ISSUE THREAD

**Issue by blimeybloke** [iandwelker/smserver#55]
So my stupid phone auto updated.  I should have blocked the updates so my fault.  Either way, I am on 14.1 jailbreak and the app runs, and I can use it but then the daemon crashes after a few minutes.  I can test anything you need.  I feel naked without this on my windows computer lol

thanks

**Comment by iandwelker** [comment]
Could you give more details about what you mean by saying that it 'crashes'? SMServer doesn't use a daemon at all, so I'll need more information before I can determine exactly what's happening. Also, if you can get a crash log, that would be phenomenal.

**Comment by blimeybloke** [comment]
I am sorry, it's the same type of issue I had earlier where the daemon would just stop.

**Comment by iandwelker** [comment]
I'm sorry, but I'm really not following you at all; neither the app nor the tweak for SMServer include a daemon, so I'm very confused as to what you mean when you say that 'the daemon' is stopping. Could you expand on that and give a more detailed explanation on exactly what you are running into and why you believe a daemon is 'stopping'?

**Comment by blimeybloke** [comment]
Well, it seems 1 single imessage contact was causing the crash of the app on the iPhone.  I deleted that message and now everything is ok.  It is kind of strange and sorry for being so confusing.  We can close this as it appears to be working now.  Not sure what was up with that message exchange though.

**Comment by iandwelker** [comment]
Well, I'm glad to hear it's all working now. Feel free to reopen this if you run into the same thing again.
