### ISSUE TITLE
Chats not loading and server not staying on (iOS 14.2, odysseyn1x 2.7, iPhone 6S)

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#56]
![SMServer - Brave 11_9_2020 5_24_32 PM](https://user-images.githubusercontent.com/53708281/98603752-a0a9c080-22b0-11eb-8647-64d21c7efb3b.png)

**Comment by iandwelker** [comment]
I'm still on 14.0 at the moment, but I'm planning on updating to 14.2 soon, so I'll update this issue once I've updated and get a moment to check it out.

**Comment by iandwelker** [comment]
I've just updated (iPhone 6s, iOS 14.2, checkra1n 12.0), and I'm not running into any issues; it seems to be working just as before. Were you able to try this app at all on plain checkra1n (before setting up odysseyra1n)? Also, would you be able to get a log from the app or a crash log if the app is crashing?

**Comment by CSab6482** [comment]
![iOS 14 2 Fix](https://user-images.githubusercontent.com/53708281/98682649-2883df00-2332-11eb-9a10-53c82e8819b5.JPG)
Yes, it was a problem unrelated to the tweak and I was able to fix it with this solution from [https://www.reddit.com/r/jailbreak/comments/jqqyhu/tutorial_how_to_fix_checkra1n_0120_app_not/](this) thread.
