### ISSUE TITLE
Memoji doesn't display properly (server running from iOS 14.2, odysseyn1x 2.7, iPhone 6S) Second picture from the iPhone, Third from a Samsung Galaxy S10e on OneUI 2.5, AirMessage 0.5.7[macOS 10.14.6]

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#57]
![No Memoji](https://user-images.githubusercontent.com/53708281/98752784-ea69d800-2390-11eb-8f0a-537eb423336b.jpg)
![ios](https://user-images.githubusercontent.com/53708281/98752786-eb026e80-2390-11eb-8d3e-4e686b59e66a.png)
![android](https://user-images.githubusercontent.com/53708281/98752787-eb026e80-2390-11eb-9c45-d859eee045bf.jpg)

**Comment by iandwelker** [comment]
Could you check the browser console for errors? I can view memojis just fine in my web interface, so I expect there was just an error with loading in the image. If there are no errors, could you paste the link for the image here? It should be something like `/data?path=...-sticker.png`

**Comment by CSab6482** [comment]
How do I check the browser console?

**Comment by iandwelker** [comment]
Right click > Inspect (or 'Inspect Element') > Click on the tab that says 'Console'

**Comment by CSab6482** [comment]
No errors, the link is /data?path=/bacf53e2125593953ce304d155b527f3-BBF369D0-2625-4164-B5C3-6440FC61693B_AK299001_b81d04cb4c37c2410ade0d8b64bb7f66_thumbs_down/BBF369D0-2625-4164-B5C3-6440FC61693B_AK299001_b81d04cb4c37c2410ade0d8b64bb7f66_thumbs_down.png

**Comment by CSab6482** [comment]
I tried it with another Memoji too. It gives me a right click option to load the image but doesn't load. Link is /data?path=/6f5c5b9e8f42c1bd52c815012a85f27f-6f5c5b9e8f42c1bd52c815012a85f27f-sticker/6f5c5b9e8f42c1bd52c815012a85f27f-sticker.png I will try another browser.

**Comment by CSab6482** [comment]
![data ( Image) - Mozilla Firefox 11_10_2020 9_33_24 PM](https://user-images.githubusercontent.com/53708281/98758301-733a4100-239c-11eb-87b5-806e9cde3a16.png)
I got this in FireFox

**Comment by CSab6482** [comment]
![Firefox Error](https://user-images.githubusercontent.com/53708281/98758386-ab418400-239c-11eb-9e64-df933d8f1dec.JPG)
FireFox Console

**Comment by CSab6482** [comment]
![Brave Error](https://user-images.githubusercontent.com/53708281/98758821-a3ceaa80-239d-11eb-8e3d-d935d8355aa1.JPG)
And here it is in Brave

**Comment by iandwelker** [comment]
Alright, I found what the issue was: Some memoji are stored in `/var/mobile/Library/SMS/Attachments/` as regular attachments, but some are stored in `/var/mobile/Library/SMS/StickerCache/` instead, so I just allowed the app to load attachments from that directory as well and it's started working for all memoji, both old and new (for me, at least). I'll hopefully release version 0.5.4 soon, and it should have that fix implemented.

**Comment by iandwelker** [comment]
0.5.4 is out now; could you try it out and let me know if it fixes the issue for you as well?

**Comment by CSab6482** [comment]
Yes! All the memojis look great. I also appreciate the added bubble tails, thank you so much!
