### ISSUE TITLE
Very specific bug regarding tapbacks (iOS 14.2, odysseyn1x 2.7, iPhone 6S, SMServer 0.5.4)

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#59]
This is a really specific and a bit of an inconsistent bug. When using a tapback on a message in a chat I have open on SMServer and on my iPad, and then I click the chat to refresh, that message disappears (both texts and images). Sometimes it comes back, sometimes it doesn't. I've had one text message come back but one image and one emoji text disappeared for good.

**Comment by iandwelker** [comment]
While working on the next version, I've rewritten the section that displays tapbacks to fix some issues, so this may be fixed when the next version is released. I'll update this task once I release it, and you can let me know if it appears to be fixed.

**Comment by iandwelker** [comment]
Version 0.6.0 is now out -- try it out and let me know if you're still running into this same thing

**Comment by CSab6482** [comment]
Thank you! This particular issue is solved however I now have problems with the server restarting when opening certain chats. That may just be specific to me however so I'll look into it.
