### ISSUE TITLE
Application crashes on trying to send a message

### ISSUE THREAD

**Issue by boomcan90** [iandwelker/smserver#61]
Trying to send a message via the web interface crashes the application. 

Settings, the following options enabled, everything else is disabled: 

- Requires Authentication
- Enable backgrounding 
- Enable SSL 

Crash Log: 

https://paste.ee/p/fse6m

**Comment by iandwelker** [comment]
Could you install [this version of libsmserver](https://byu.box.com/s/a3d8kgpskkb5zdprh6zpk5zykph1szce), run an ldrestart, and try again?

**Comment by boomcan90** [comment]
This fixed the issue with the crashing, however whenever I send a link, the preview text is always the previous message. Closing and reopening the chat fixes that.

**Comment by iandwelker** [comment]
I may be misunderstanding what you mean, but does it feel similar to what is currently being discussed in #37? If so, please try downloading the new versions of libsmserver and SMServer listed there and let me know if that fixes it

**Comment by boomcan90** [comment]
Same issue as above on inserting image from local machine, works fine when importing from camera roll on iOS.

**Comment by boomcan90** [comment]
It was a similar issue - Seems to have been fixed. Might be having some issues with notifications - will test a bit more and get back. Marking this as closed in the meantime.
