### ISSUE TITLE
SMServer crashes whenever I try to send a message on the web browser.

### ISSUE THREAD

**Issue by OrangeMan74** [iandwelker/smserver#62]
Title.  I've got "Require Authentication", "Enable backgrounding", and "Enable SSL" on in the settings.  Crash log from Cr4shed: https://pastebin.com/4dg9i1qE

**Comment by iandwelker** [comment]
Could you completely uninstall and reinstall libsmserver? I accidentally uploaded a broken version earlier today, then quickly uploaded a fixed version, but you may have installed the broken version in that short time.

**Comment by OrangeMan74** [comment]
> Could you completely uninstall and reinstall libsmserver? I accidentally uploaded a broken version earlier today, then quickly uploaded a fixed version, but you may have installed the broken version in that short time.

I tried updating it, and the version Cydia decided to download was probably the broken 0.5.1, and I tried downgrading to the other 0.5.1, and it seems to have fixed it.  The initial problem was on 0.5.0 for reference.

**Comment by iandwelker** [comment]
Alright, I'm glad it's fixed. I'll close the issue.
