### ISSUE TITLE
SMServer causing problems when sending messages

### ISSUE THREAD

**Issue by gainb** [iandwelker/smserver#63]
On the older version of libmserver, SMServer would instantly crash when sending messages. On the newer version, springboard crashes when I send a message. 
[Crashlog](https://github.com/iandwelker/smserver/files/5620949/text.txt)

**Comment by iandwelker** [comment]
Could you try completely uninstalling and reinstalling libsmserver? As I stated in #62, I accidentally uploaded a broken version of libsmserver to twickd, then quickly uploaded a fixed version. However, you may have installed the broken version, so a complete uninstall and re-install should fix it.

**Comment by gainb** [comment]
I tried that, still crashed my springboard

**Comment by gnawh** [comment]
same issue. all different settings - some threads crash some don't (not sure if it's the location thing, as I've shared location with one and it seems fine). sending message restarts my springboard, however. 
tried with all tweaks disabled as well (besides dependencies). 
didn't realize how much i depended on this, will try and downgrade until it's fixed.

**Comment by iandwelker** [comment]
I released version 0.6.1 of SMServer and 0.5.2 of libsmserver - Could you upgrade and try them out to see if they fix this?

**Comment by blxrr** [comment]
Not the OP, but I’m having the same issue with 0.6.1 of SMServer and 0.5.2 of libsmserver.

**Comment by gnawh** [comment]
works for the majority - now only those certain threads cause crash.

**Comment by iandwelker** [comment]
If someone who is having this issue (@blxrr or @gainb) could get a log (or even the last ~30 lines from a log) from the app as described in the readme of this repo, that would be much appreciated and would help me a lot in figuring out where this issue is stemming from.

**Comment by blxrr** [comment]
So, @iandwelker, I am no longer receiving a crash/respring, but what I am recieving is a `<Debug>: SMServer_app: WARNING: The websocket failed to start. This will prevent you from receiving new messages.` now. My messages are sending, but not showing on the web side of things which I think that's the issue until I reload the page then they show up. Any fixes to that?

**Comment by iandwelker** [comment]
@blxrr  that normally occurs when you are trying to run the websocket and the server on the same port. To fix that, you'll need to open the settings, change the websocket port to something that is different from what is shown as the server port in the main app view, restart the app, and try to run the server again.

**Comment by iandwelker** [comment]
I know this issue may be dead, but it may have just been fixed with version 0.6.2 of libsmserver (see [this issue](https://github.com/iandwelker/libsmserver/issues/1)); if any of you are still experiencing this, could you try out the latest update (of both SMServer and libsmserver) and let me know if you're still running into this?

**Comment by iandwelker** [comment]
Alright, calling this issue as dead. Feel free to reopen if anyone is still running into this.
