### ISSUE TITLE
No messages are loading

### ISSUE THREAD

**Issue by nate-moo** [iandwelker/smserver#7]
I press the more chats button and nothing happens, even when using the curses based client nothing happens. The response when looked at in the dev tools is an empty JSON array (as seen below)

iPhone 8 - iOS 13.5 - Unc0ver
latest release of smserver

```
{ "chats": [

]
}
```

**Comment by iandwelker** [comment]
Maybe a dumb question: Are you certain you have more conversations than are already displayed on the page? run `document.getElementsByClassName("chats-list")[0].children.length` in your browser console to check how many are displayed.

Also, I just noticed that I accidentally switched the default number of chats to load and the default number of messages to load; if you didn't change them from the defaults, it would load 200 chats and 60 messages, as opposed to 60 chats and 200 messages (as the settings would state if you looked at them). Could you try changing the values for how many chats & messages to load, reloading the app, and checking if you still run into this issue?

**Comment by nate-moo** [comment]
It returns 1?
![image](https://user-images.githubusercontent.com/40650681/90077198-8c652000-dccf-11ea-898a-d16ac3ceddd4.png)
also the default values were 60 chats and 200 messages for me at least.

**Comment by iandwelker** [comment]
Ah, ok I was under the impression that it had already loaded in some conversations, as opposed to just didn't load any conversations at all. And I'm aware that the settings section of the app may have stated that it would load 60 chats and 200 messages, but if you didn't change those values, the app would actually load 200 chats and 60 messages.

Down near the bottom of the readme, it gives instructions on how to get a log from the app. Do you think you could run through those steps and attach the log here or DM it to me? This appears to be an error inside the app (as opposed to something with the web interface), so I'll need to examine a log to find the issue.

**Comment by nate-moo** [comment]
sure, I'll send the log in a few minutes, along with changing the values and report back

**Comment by nate-moo** [comment]
Logs: https://hastebin.com/mubanajilo.cs
Changing the values didn't do anything, still loading nothing

**Comment by nate-moo** [comment]
I noticed this:
```Aug 12 21:39:34 iPhone SMServer(com.ianwelker.smserver.debugging)[1260] <Debug>: SMServer_app: WARNING: error opening database```
and think it may have something to do with the chats not loading

**Comment by nate-moo** [comment]
And there are a couple of these:
```Aug 12 21:39:34 iPhone SMServer(com.ianwelker.smserver.debugging)[1260] <Debug>: SMServer_app: WARNING: error preparing select: out of memory```

**Comment by iandwelker** [comment]
Yeah, your app is failing to open the database to read it. I've already verified that it works on unc0ver and 13.5, so it shouldn't be anything to do with read/write permissions; I'm still working on figuring out exactly what is causing it.

**Comment by nate-moo** [comment]
ok, if there is anything else you would like me to do I would gladly do it :)
I'm going to be sleeping for the next few hours so if you ask for something I prob wont respond until at least 8 EST

**Comment by nate-moo** [comment]
Is it possible that one of my message threads has too many messages, or one of my contacts having too many numbers? (I have a contact with 200+ phone numbers)

**Comment by iandwelker** [comment]
No, that shouldn't cause any issues; I have 500+ conversations, some with 40,000+ messages and everything works fine. Plus, contact information is not stored in the sqlite database that is failing to open.

**Comment by nate-moo** [comment]
Ok, after looking at the other issue I can also send messages through the New box

**Comment by iandwelker** [comment]
I've updated this repository with new packages; you can find them under the `package` subdirectory. Could you download the latest deb from here, install it, and let me know if it fixed your issue?

**Comment by nate-moo** [comment]
It didn’t work :/

**Comment by iandwelker** [comment]
I added more comprehensive logging in the latest version, so could you get me a log again, just like last time?

**Comment by ayserjamshidi** [comment]
@nate-moo What version of unc0ver are you jailbreaking with?  My SMServer install would not load any messages just like yours with unc0ver versions 5.0.0 and 5.0.1, but updating to the latest 5.3.1 allowed SMServer to work as intented.

**Comment by nate-moo** [comment]
@ayserjamshidi I am currently on 5.0.0, I'll update it and test it along with logs before and after

**Comment by nate-moo** [comment]
[u0 5.0.0](https://hastebin.com/kexohujaqo.xml)
I have concluded that it was uncover, I'm not going to send logs bc they contain phone numbers. I switched to checkra1n (it was a major pain in the butt bc substrate had conflicts and other BS) and it works. 
You should prob mention this somewhere that you should be on the latest jailbreak software to prevent this from happening \:)
Thank you all for the help, and I hope you have a good rest of your day/night

**Comment by creditcreate** [comment]
@nate-moo Do you have any guide to switch from unc0ver to checkra1n? Is there no way using unc0ver?

**Comment by iandwelker** [comment]
@nate-moo & @ayserjamshidi  -- thanks for solving it; I'll work something into the package description and repo letting people know that they need to be on the latest version of their jailbreak. I'll close this issue.

@creditcreate -- I've switched back and forth a few times, I've found the best way is to backup my tweaks offline using batchomatic, then restore rootfs to get rid of the jailbreak, re-jailbreak with the new jailbreak, and then restore tweaks using the deb that I made at the beginning. It hasn't failed me yet.

**Comment by nate-moo** [comment]
@creditcreate If you're comforable with the command line and SSH, you can go in and remove the substitute package with dpkg and install mobile substrate with apt, without having to reinstall all tweaks 

this set of commands worked for me though they might change depending on the mobile substrate version
run the commands in this order
1. `apt download mobilesubstrate`
2. `dpkg -r science.xnu.substituted`
3. `dpkg -i mobilesubstrate_0.9.7101_iphoneos-arm.deb` if doesnt work then change the version number to match yours

**Comment by ayserjamshidi** [comment]
@iandwelker 
> Do you have any guide to switch from unc0ver to checkra1n? Is there no way using unc0ver?

Simply update to the latest version of unc0ver as suggested earlier.  I remember the early versions of unc0ver got updates for allowing some jail access for apps that requested it, or something along those lines, so that might be why old versions of it don't work.
