### ISSUE TITLE
Failed tapbacks, one even caused my server to restart + phone to boot into safe mode (iPhone 6S, iOS 14.2, odysseyn1x 2.8)

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#70]
![20210110_182226](https://user-images.githubusercontent.com/53708281/104138274-0aa61b00-5371-11eb-8988-ab9af8802677.jpg)
Last night I had this happen on just about every tapback I sent. Today that number went down to about 1 in 5, but as the title says, one failure was enough to send my phone into safe mode. Let me know what settings I can turn on/logs I can send for better debugging (I also did a full uninstall/reinstall of both SMServer and libsmserver)

**Comment by iandwelker** [comment]
This seems similar to issue #66. Could you close this issue and add this information there?

**Comment by CSab6482** [comment]
Done, thank you 👍
