### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by tt531** [iandwelker/smserver#71]
iPhone XS
Unc0ver
iOS 13.5
Installed with Cydia 
SMServer 0.7.0
libsmserver 0.6.0

It crashes as soon as I login on my browser.
Crash report attached. 

[text.txt](https://github.com/iandwelker/smserver/files/5797907/text.txt)

**Comment by iandwelker** [comment]
Thanks for including the crash report &mdash; due to that, I'm fairly certain I know what's happening and it should be easy to fix. Just to make sure that I've got the right idea, though, could you get me a log from the app, as is described near the bottom of the README of this repository?

**Comment by iandwelker** [comment]
It was released a bit ago, but this issue should be fixed in version 0.7.1 of SMServer. Could you confirm?

**Comment by tt531** [comment]
It’s fixed.
