### ISSUE TITLE
Unable to send any messages

### ISSUE THREAD

**Issue by wonkieinc** [iandwelker/smserver#72]
I’ve tried literally every version, and none of them have been able to send or receive a single message on my phone. Shows all messages that are on my phone at the time of enabling, sent messages just disappear and don’t show on my phone, new messages don’t show up

**Comment by iandwelker** [comment]
Could you list what version of libMRYIPC you have installed onto your device, along with what device you're using, what jailbreak (and version), and iOS version?

**Comment by wonkieinc** [comment]
V2.0 of libMRYIPC

iPhone 8
iOS 13.5
u0 5.3.1

**Comment by iandwelker** [comment]
Would you be able to get a log from your device, as described in the readme of this repo?

Also, if possible, could you complete the following steps:
1. Install the package `cURL` onto your host device using your package manager
2. SSH into your host device
3. In the following step, replace `<chat>` with your full phone number and `<pass>` with your server's password.
4. Run the following command on your host device's terminal while SSH'd in:
```sh
addr="https://$(ipconfig getifaddr en0):8741" && curl -k "${addr}/password=<pass>" && curl -k -s -o /dev/null -D - -F "text=test message" -F "chat=<chat>" "${addr}/send"
```

**Comment by wonkieinc** [comment]
So I re-installed SMServer after upgrading Substitute, and it now appears to be working

I guess this issue can be closed, thanks for your help and sorry for the delay
