### ISSUE TITLE
Enabling SSL wont let SMServer Web Client show up

### ISSUE THREAD

**Issue by midi1996** [iandwelker/smserver#74]
Phone: iPhone 8
iOS: 14.1
Jailbreak: Checkra1n 0.12.2
SMServer: 0.7.0 (Cydia)
linsmserver: 0.6.0 (Cydia)
libMRYIPC: 2.0 (Cydia, BB)

When I enable SSL the website doesn't seem to load on any of my browsers (tried FF, Chromium Edge and Chrome), disabling it works, but doesn't that create a big security concern? (even if there is a password)

Saw #38 and #41 and they show similar symptoms.

**Comment by iandwelker** [comment]
Could you verify that you're connecting explicitly with `https://` instead of `http://`, and could you also verify (to the best of your knowledge) that no firewall on your client device is blocking your connection to the host device?

**Comment by midi1996** [comment]
It seems that on Edge it doesnt work with https forced for some reason while chrome works, it does complain about the certificate. Any way to add it to trusted certs? It says to connect to the websocket but how?

**Comment by iandwelker** [comment]
For the certificate, you can download SMServer's certificate from [here](https://github.com/iandwelker/smserver/raw/master/src/SMServer/cert.der), and add it to your system's certificate trust. It shouldn't throw errors about a bad certificate after that.

For the websocket &mdash; the url that it tells you to visit is incorrect in version 0.7.0. You'll just need to replace the `wss` (or `ws`, if you're not using https) part of the url that it shows you in the alert with `https` (or `http`, if you're not using https), visit that url, then trust the certificate that it throws an error for there.

**Comment by midi1996** [comment]
That worked, I hope you can add a way to use personal certificates too. Thanks.

**Comment by iandwelker** [comment]
I am working on implementing functionality to easily generate a personal certificate for the app to use, and I'll update this task once I've got it fully working.

**Comment by iandwelker** [comment]
The app now automatically generates a unique certificate once you install version 0.7.1 (don't worry, though, once it's generated a unique certificate this first time, it won't do it whenever you upgrade, so you can use this new certificate for each version from now on). I'll close this issue now.
