### ISSUE TITLE
No contacts photos (big icons) and weird empty chat entries

### ISSUE THREAD

**Issue by midi1996** [iandwelker/smserver#75]
When I open the Web Client, I get some highlighted chat pictures at the top with weird artifacts like this:

![image](https://user-images.githubusercontent.com/4874726/104368985-1df5e980-551d-11eb-87c2-7bffa340b062.png)

Those two contacts indeed do not have any profile picture.

also the one in the middle with a UUID, I have no idea what it is and it's an empty chat and when sending a message to it, it shows up as "Undefined" on Messages app.

Phone: iPhone 8
iOS: 14.1
Jailbreak: Checkra1n 0.12.2
SMServer: 0.7.0 (Cydia)
linsmserver: 0.6.0 (Cydia)
libMRYIPC: 2.0 (Cydia, BB)

(also sorry if I'm opening a new issue, I think that different issues require different threads)

**Comment by iandwelker** [comment]
I appreciate that you're opening different issues for each problem &mdash; it helps me keep track of them.

With regard to the chats whose icons aren't showing up: Are they group chats? If not, are they iMessage or SMS conversations? And if iMessage, are you sending texts to an email address or to a phone number?

Also, to clarify: Do you have 4 pinned conversations in the iMessages app on your host device? And if so, what type of conversation is the one in the middle (with the UUID)? (e.g. group chat, SMS, iMessage with email, iMessage with phone number)

**Comment by midi1996** [comment]
Actually that is a group message, but the weird thing is I only has one group and one person pinned in the app. I think that iCloud messages may be freaking this thing out, on macOS i had 4 pins of which 3 were people (iMessage) and one groupe (iMessage), but on my iPhone it somehow didnt sync all discussions (which also got erased in icloud and affected macOS, no idea why or how). It seems that there was a sync issue and probably whatever SMServer was reading from got the old synced pins. And yes groups are not shown in SMServer web client but an UUID.

**Comment by iandwelker** [comment]
Alright, it's taken me a bit to figure this out but it should be all fixed up for the next update of SMServer. I've tested out pinned group chats on my end as well, and they appear to work just fine. I'll update this task once I've released it to get confirmation that it's been fixed for you too.

**Comment by iandwelker** [comment]
Alright, 0.7.1 has been release. @midi1996 could you update and let me know if you're still running into any issues with this? If you aren't, feel free to close this issue.

**Comment by midi1996** [comment]
![image](https://user-images.githubusercontent.com/4874726/105159483-6d38ad00-5b0f-11eb-9633-c2d3128867f3.jpeg)

It's working although it didnt get the group picture.

**Comment by iandwelker** [comment]
Ah yes, thank you for letting me know -- to be honest, I had no idea that group chats could have profile pictures. This should be an easy fix, and I'll have it done by the next version.

**Comment by iandwelker** [comment]
Sorry it took so long, but I've got group chat images implemented now (it's a somewhat hacky workaround so it may not be certain to work on your end); it'll be implemented in version 0.7.3. Once that's out, let me know if it works for you.

**Comment by midi1996** [comment]
Sure! Thanks, ill be testing it once it's out!

**Comment by iandwelker** [comment]
Alright, the latest update is out &mdash; could you try it out and let me know if you can see group chat pictures now? If so, feel free to close this issue.

**Comment by midi1996** [comment]
Just got the update and it's working! 

![image](https://user-images.githubusercontent.com/4874726/108611769-2675f580-73e2-11eb-8c57-99daa3b906d8.jpeg)

I pinned 2 groups, one with a pic (spanish laughing dude) and one without. 👍
