### ISSUE TITLE
Unable to open in Rambox

### ISSUE THREAD

**Issue by wonkieinc** [iandwelker/smserver#78]
I am trying to access my SMServer WebUI from within [Rambox ](https://rambox.pro/#home) but cannot get the UI to load at all.

Is this something that can be resolved on the SMServer end?

Kindest Regards,
Luke.

**Comment by iandwelker** [comment]
I don't have too much time to test this, but in my limited time, it appeared that it was an issue with Rambox not trusting self-signed certificates. I was able to get it to work just fine with SSL disabled, but I would expect that's less than desirable for you. You could try downloading SMServer's certificate from [here](https://github.com/iandwelker/smserver/raw/master/src/SMServer/cert.der), adding that to your system's certificate root trust, and see if that fixes the problem of nothing loading when SSL is on.

**Comment by wonkieinc** [comment]
Tried that already, Rambox is just weird with "invalid" certs, the issue being the cert for smserver.com isn't for iphone.local 

Is there a way that I can use my own LetsEncrypt SSL for this?

**Comment by wonkieinc** [comment]
Alternatively, is there any way that I can toggle this over SSH/Activator? 

If so, I can configure it to auto-start with my USB tunnel that I already use for VNC

**Comment by iandwelker** [comment]
Yes, you can use your own certificate; here's the easy way:
1. Download the script located at `/package/deb/DEBIAN/postinst` in this repo
2. Remove line 10 (the one with `[ -f "${dir}/smserver_cert_pass.txt" ] && return`)
3. On line 22, change `smserver.com` to the hostname you need (e.g. `iphone.local`)
4. ssh into your iDevice as root, transfer the modified script over, and run it. It should automatically generate a new certificate with your new hostname, and it *should* work flawlessly with SMServer.

As far as I can think of, there's no easy way to toggle SSL/encryption on/off with SSH or Activator; sorry about that.

**Comment by wonkieinc** [comment]
Thanks for the response, tried that to no avail, raised an issue with Rambox

Regarding the SSH/Activator toggle I was menaing for SMServer in general, not just encryption. Is this available or possible by chance?

**Comment by iandwelker** [comment]
I've never used activator before, but if you can open an app with an activator action, then it would be possible. You could turn on "Start server on app launch" in SMServer's settings, and then launch it with activator when you would like the server to start. However, I can't test this solution, so I'm not certain it will work.

**Comment by iandwelker** [comment]
@wonkieinc Update: You can now run this app over SSH or set it to run as a daemon on your device. If you run `/Applications/SMServer.app/SMServer` with any commandline arguments, it acts as a cli tool. To make it run forever in the background, you'd just need to run `/Applications/SMServer.app/SMServer -b &`

You can also set it to run as a daemon by downloading [this file](https://github.com/iandwelker/smserver/blob/master/docs/com.ianwelker.smserver.plist) and following the instructions in the comment at the top of its contents.

**Comment by wonkieinc** [comment]
Thanks Ian, great update!
