### ISSUE TITLE
Request to send an image/video/attachment first when sending it with a text caption

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#84]
Basically a copy and paste of my issue posted [here](https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/144)

**Comment by iandwelker** [comment]
I would like to add this, but how do you recommend it be implemented? Should it just be another toggle in the settings section of the app? Or would there be something that you could send with the API request to signify that the image should go first?

**Comment by CSab6482** [comment]
Now that is a good question. I've also noticed there's no real defined way of attaching multiple attachments to an SMServer message and choosing in which order they send. Maybe 2 birds can be killed with one stone here? That is, if there is any way to detect in which order the attachments were selected to begin with.
![order of files](https://user-images.githubusercontent.com/53708281/106997595-2a9ee380-6751-11eb-943a-e4262f212b4a.JPG)
For example, here I selected two files, and in the File Name drop-down bar, they show up in order from right to left. However, when I send these attachments, there is no guarantee that they'll send in the order I selected them in. Currently, all iMessage forwarding software I've used has had this problem, though Tagavari of AirMessage claims to have solved it in an upcoming update.
![u-Tagavari](https://user-images.githubusercontent.com/53708281/106997904-b284ed80-6751-11eb-9399-05cb42d29e7e.JPG)
post [here](https://www.reddit.com/r/AirMessage/comments/krqfcd/airmessage_development_update/)

I think these issues could be related, but if my tangent was too irrelevant and long let me know as well. I hope it made sense. Thank you again for such an amazing app and for keeping it free and open source.

**Comment by CSab6482** [comment]
https://github.com/sgtaziz/WebMessage/issues/33#issuecomment-779964183

**Comment by sgtaziz** [comment]
All I did was initWithText:nil when initiating the composition, then using the appendMedia followed by the appendText function. This will sort the NSAttributedString properly to show attachments then the text, which is the way the iOS messages app does it. I don't think a toggle for this is necessary

**Comment by iandwelker** [comment]
Interesting; I guess I'll try that out if it seemed to work for you. Thanks for the tip!

**Comment by iandwelker** [comment]
This should be fixed in the latest update &mdash; feel free to close the issue if it's fixed for you too.

**Comment by CSab6482** [comment]
It works, but displays incorrectly on SMServer. Or, on SMServer is it meant to display with the text first? If so then it is all good

**Comment by CSab6482** [comment]
I'm in a really weird spot. Sending pictures now boots my phone into safe mode. I'll download a crash app or something to be able to get the logs because I have no idea what could have caused this. This started happening after I tested this issue and then [issue 85](https://github.com/iandwelker/smserver/issues/85)

**Comment by CSab6482** [comment]
This time I received a crash file for both the springboard and SMServer
[SpringBoard crash.txt](https://github.com/iandwelker/smserver/files/6016898/SpringBoard.crash.txt)
[SMServer crash.txt](https://github.com/iandwelker/smserver/files/6016899/SMServer.crash.txt)

**Comment by CSab6482** [comment]
Okay, I figured out the problem. On 0.7.3, pictures cannot be sent on their own, they must be sent with a caption. On SMServer, the text shows first and then the image does, and on iOS the image shows first and then the caption. Also, when selecting multiple attachments, they send in alphabetical order every time no matter what order they're selected in.

**Comment by iandwelker** [comment]
Alright, I've poked around and fixed the crash issue. In the next version, you'll be able to send iMessages that are all attachments, all text, or a mix of the both, and the image will show before the text. Not quite certain why I set it so that the text showed before the image in the last version, but that will be fixed in the next version.

**Comment by iandwelker** [comment]
Version 0.7.4 is out on twickd.
