### ISSUE TITLE
Sending texts with text in the subject field but no text in the main body does not work

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#85]
This is an interesting one, a message sends, but there's nothing in it. And it's not nothing like a blank and small blue bubble: it's actually just an empty spot on the screen. Also, two enter presses are required to send it 

https://user-images.githubusercontent.com/53708281/107098342-fec93f80-67dc-11eb-99d8-b1322c5c360c.MP4

https://user-images.githubusercontent.com/53708281/107099779-9d0ad480-67e0-11eb-8b12-5ed6eb00f794.mp4

![IMG_0312](https://user-images.githubusercontent.com/53708281/107098350-012b9980-67dd-11eb-939e-60656b8e7a38.PNG)

**Comment by iandwelker** [comment]
What the heck -- so what happens if you try to send a text with only a subject and no body in the iMessages app on your phone? Does that show up in the iMessages app and/or SMServer?

**Comment by CSab6482** [comment]
> What the heck -- so what happens if you try to send a text with only a subject and no body in the iMessages app on your phone? Does that show up in the iMessages app and/or SMServer?

Yes, that is what I showed in the first video

**Comment by iandwelker** [comment]
Alright, I just pushed an update for SMServer that should include this fix &mdash; let me know if it's fixed for you as well; close this issue if so.

**Comment by CSab6482** [comment]
It works perfectly, thank you so much!
