### ISSUE TITLE
Typing long messages on Android results in graphical bugs

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#87]
https://user-images.githubusercontent.com/53708281/107454097-64d5ff80-6b1a-11eb-8f5a-4c42770390e5.mp4

I tested this on iOS and everything worked as expected

**Comment by iandwelker** [comment]
Dang, android browsers really love to have issues, huh? I'll check this one out and try to figure out why it's doing that.

**Comment by ArmandoU6** [comment]
Yep. Same issue here.

**Comment by iandwelker** [comment]
https://github.com/iandwelker/smserver/issues/79#issuecomment-803684385

**Comment by CSab6482** [comment]
This has been fixed with the 0.8.0 release! Thanks so much :D. I am unfortunately still facing issue #79 with group chats on Android however
