### ISSUE TITLE
Scrubbing through a video only works when going back to the beginning. Server - iPhone 6S iOS 14.4 odysseyn1x 2.9 (based on checkra1n 0.12.2) SMServer 0.7.2 | Client - Dell Inspiron 7586 on Windows 10 in Brave browser (Chromium based)

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#93]
See [here](https://github.com/sgtaziz/WebMessage/issues/32) and [here](https://stackoverflow.com/questions/8088364/html5-video-will-not-loop/9549404#9549404)

https://user-images.githubusercontent.com/53708281/108585804-7c7e6680-7318-11eb-9556-30b62a655578.mp4

**Comment by iandwelker** [comment]
Alright, I've got this fixed (in my limited testing). I'll ship the fix with the next update.

**Comment by CSab6482** [comment]
Fixed! Thank you so much
