### ISSUE TITLE
Cannot send images on 0.7.3 without a caption

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#96]
Attempting to send images or attachments on their own boots the server device into safe mode, but sending with a text caption doesn't. Here are my crash logs and other things copied from issue #84
![108610095-ef332480-73a0-11eb-8a2f-77e9c2b4dc8e](https://user-images.githubusercontent.com/53708281/108615632-253dcc00-73d4-11eb-9f8b-387799332297.jpg)
[2021-02-20_5-21_pm.txt](https://github.com/iandwelker/smserver/files/6017195/2021-02-20_5-21_pm.txt)
[SpringBoard image no caption crash.txt](https://github.com/iandwelker/smserver/files/6017196/SpringBoard.image.no.caption.crash.txt)
[SMServer image no caption crash.txt](https://github.com/iandwelker/smserver/files/6017197/SMServer.image.no.caption.crash.txt)

[Springboard Image No Caption Crash 2-22-21.txt](https://github.com/iandwelker/smserver/files/6024917/Springboard.Image.No.Caption.Crash.2-22-21.txt)
[SMServer Image No Caption Crash 2-22-21.txt](https://github.com/iandwelker/smserver/files/6024918/SMServer.Image.No.Caption.Crash.2-22-21.txt)

**Comment by sgtaziz** [comment]
pls don't blame me

**Comment by iandwelker** [comment]
> pls don't blame me

@sgtaziz Lol you're all good, no stress &mdash; this'll be fixed in the next update.

**Comment by iandwelker** [comment]
Version 0.7.4 is out on twickd.
