### ISSUE TITLE
Request to mirror the thumbs down to match iOS and macOS

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#98]
![](https://user-images.githubusercontent.com/53708281/108636538-e94a4b80-7453-11eb-9c7b-2d4d2e8db275.png)
![SMServer Thumbs down](https://user-images.githubusercontent.com/53708281/108767148-0a7a6d00-7524-11eb-9838-2c3b70a60629.JPG)
https://github.com/sgtaziz/WebMessage/issues/59#issuecomment-782914721

**Comment by iandwelker** [comment]
Yeah, I can do that. 

Also, what are your thoughts on the black highlight/shadow behind the tapback choice icons in the web interface? I used to like them, but I'm really not that much of a fan of them anymore. Would you be ok with them just being removed?

**Comment by CSab6482** [comment]
I think they're alright but I wouldn't mind if they were removed 👌

**Comment by iandwelker** [comment]
Version 0.7.4 is out on twickd.
