### ISSUE TITLE
Message sent from web client stalled then duplicated earlier messages

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#99]
![Duplicated received message](https://user-images.githubusercontent.com/53708281/108768052-33e7c880-7525-11eb-8330-c11b463992f4.JPG)
<img width="375" alt="iOS" src="https://user-images.githubusercontent.com/53708281/108768059-35b18c00-7525-11eb-82b6-a04187cec107.png">
At the red line I sent a message from the web client that you can see did successfully go through, however I was never able to see this on SMServer. It stalled for a bit, then duplicated the message, and then I got a popup about the server restarting. After the popup, my phone did not crash or respring, and I was simply able to reload the web client and everything worked. I didn't have to put my password in again.

**Comment by iandwelker** [comment]
Sorry that I haven't yet done anything with this &mdash; have you run into this issue much since you originally posted or has it just been the one time? It'll be hard for me to debug if it's only an isolated incident.

**Comment by CSab6482** [comment]
Yeah, it was just the once. I'll close it for now and if it happens again I'll comment/reopen
